-- =============================================================================================
-- BizApps Accounting v0.1.x -- Metadata_Sync (one per release, generated by the build engineer)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --ci` against MJ_Acct_Pub: a database built from
-- migrations ONLY -- MJ core v6.1.0-edge.5, bizapps-common, bizapps-tasks, then this app's own
-- migrations -- with no prior sync of this app's metadata. The push reported 0 errors:
-- 15 created, 2 updated, 105 unchanged, 122 records.
--
-- WHY THIS FILE HAS TO EXIST, AND WHY IT COULD NOT BE GENERATED BEFORE.
-- Release seed coverage flagged 15 metadata primaryKeys in no migration: the `Accounting` action
-- category, 2 Actions with their 11 Action Params, and the ERP daily-sync Scheduled Job.
--
-- They were unshippable for a reason worth recording: `metadata/action-categories/` and
-- `metadata/actions/` had NO `.mj-sync.json`. MetadataSync only walks directories that declare
-- their entity, so it skipped both **silently** -- the push reported success over 8 of 10
-- directories and nobody saw the other two. bizapps-orders and bizapps-common have one in every
-- directory; this app was missing exactly the two that hold its Actions. Both configs are added in
-- the same change, and `directoryOrder` now names all ten directories with the categories ahead of
-- what references them.
--
-- -- SUBSTITUTION APPLIED TO THE GENERATOR'S OUTPUT ------------------------------------------
--
--   `[__mj]` -> `[${mjSchema}]`, in all 17 places it appeared.
--
-- Every proc in this file is an MJ CORE proc -- spCreateActionCategory, spCreateAction,
-- spCreateActionParam, spCreateScheduledJob, spUpdateEntityField, spUpdateEntityRelationship --
-- verified against the built database to exist in `__mj` and not in `__mj_BizAppsAccounting`.
-- Nothing here touches this app's own schema, so no `${flyway:defaultSchema}` appears; that is the
-- same split the existing V202608240216__v0.1.x__Metadata_Sync.sql uses, where this app's own
-- spCreateCurrency / spCreateGLAccountRole / spCreateJournalEntryType carry
-- `${flyway:defaultSchema}` and the core calls carry `${mjSchema}`.
-- =============================================================================================

-- SQL Logging Session
-- Session ID: 0a868c70-eb0f-4fcf-ab9c-0350fec6ff7c
-- Started: 2026-09-02T04:41:38.139Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Entity Fields (core SP call only)
DECLARE @DisplayName_d7563b80 NVARCHAR(255),
@Description_d7563b80 NVARCHAR(MAX),
@AutoUpdateDescription_d7563b80 BIT,
@IsPrimaryKey_d7563b80 BIT,
@IsUnique_d7563b80 BIT,
@Category_d7563b80 NVARCHAR(255),
@ValueListType_d7563b80 NVARCHAR(20),
@ExtendedType_d7563b80 NVARCHAR(50),
@CodeType_d7563b80 NVARCHAR(50),
@DefaultInView_d7563b80 BIT,
@ViewCellTemplate_d7563b80 NVARCHAR(MAX),
@DefaultColumnWidth_d7563b80 INT,
@AllowUpdateAPI_d7563b80 BIT,
@AllowUpdateInView_d7563b80 BIT,
@IncludeInUserSearchAPI_d7563b80 BIT,
@FullTextSearchEnabled_d7563b80 BIT,
@UserSearchParamFormatAPI_d7563b80 NVARCHAR(500),
@IncludeInGeneratedForm_d7563b80 BIT,
@GeneratedFormSection_d7563b80 NVARCHAR(10),
@IsNameField_d7563b80 BIT,
@RelatedEntityID_d7563b80 UNIQUEIDENTIFIER,
@RelatedEntityFieldName_d7563b80 NVARCHAR(255),
@IncludeRelatedEntityNameFieldInBaseView_d7563b80 BIT,
@RelatedEntityNameFieldMap_d7563b80 NVARCHAR(255),
@RelatedEntityDisplayType_d7563b80 NVARCHAR(20),
@EntityIDFieldName_d7563b80 NVARCHAR(100),
@ScopeDefault_d7563b80 NVARCHAR(100),
@AutoUpdateRelatedEntityInfo_d7563b80 BIT,
@ValuesToPackWithSchema_d7563b80 NVARCHAR(10),
@Status_d7563b80 NVARCHAR(25),
@AutoUpdateIsNameField_d7563b80 BIT,
@AutoUpdateDefaultInView_d7563b80 BIT,
@AutoUpdateCategory_d7563b80 BIT,
@AutoUpdateDisplayName_d7563b80 BIT,
@AutoUpdateIncludeInUserSearchAPI_d7563b80 BIT,
@Encrypt_d7563b80 BIT,
@EncryptionKeyID_d7563b80 UNIQUEIDENTIFIER,
@AllowDecryptInAPI_d7563b80 BIT,
@SendEncryptedValue_d7563b80 BIT,
@IsSoftPrimaryKey_d7563b80 BIT,
@IsSoftForeignKey_d7563b80 BIT,
@RelatedEntityJoinFields_d7563b80 NVARCHAR(MAX),
@JSONType_d7563b80 NVARCHAR(255),
@JSONTypeIsArray_d7563b80 BIT,
@JSONTypeDefinition_d7563b80 NVARCHAR(MAX),
@UserSearchPredicateAPI_d7563b80 NVARCHAR(20),
@AutoUpdateUserSearchPredicate_d7563b80 BIT,
@AutoUpdateFullTextSearch_d7563b80 BIT,
@AutoUpdateExtendedType_d7563b80 BIT,
@IsComputed_d7563b80 BIT,
@EmbeddedRecord_d7563b80 NVARCHAR(MAX),
@Configuration_d7563b80 NVARCHAR(MAX),
@ID_d7563b80 UNIQUEIDENTIFIER
SET
  @DisplayName_d7563b80 = N'Configuration'
SET
  @Description_d7563b80 = N'Host-tunable JSON bag (IAccountingEngineExtensionConfiguration): AsOf, Objects, ContinueOnError, plus extension-specific keys. NOT hook flags — those are class getters. NULL = class/engine defaults. ISJSON-enforced.'
SET
  @AutoUpdateDescription_d7563b80 = 1
SET
  @IsPrimaryKey_d7563b80 = 0
SET
  @IsUnique_d7563b80 = 0
SET
  @Category_d7563b80 = N'Configuration'
SET
  @ValueListType_d7563b80 = N'None'
SET
  @ExtendedType_d7563b80 = N'Code'
SET
  @CodeType_d7563b80 = N'Other'
SET
  @DefaultInView_d7563b80 = 0
SET
  @DefaultColumnWidth_d7563b80 = 150
SET
  @AllowUpdateAPI_d7563b80 = 1
SET
  @AllowUpdateInView_d7563b80 = 1
SET
  @IncludeInUserSearchAPI_d7563b80 = 0
SET
  @FullTextSearchEnabled_d7563b80 = 0
SET
  @IncludeInGeneratedForm_d7563b80 = 1
SET
  @GeneratedFormSection_d7563b80 = N'Category'
SET
  @IsNameField_d7563b80 = 0
SET
  @IncludeRelatedEntityNameFieldInBaseView_d7563b80 = 0
SET
  @RelatedEntityDisplayType_d7563b80 = N'Search'
SET
  @AutoUpdateRelatedEntityInfo_d7563b80 = 1
SET
  @ValuesToPackWithSchema_d7563b80 = N'Auto'
SET
  @Status_d7563b80 = N'Active'
SET
  @AutoUpdateIsNameField_d7563b80 = 1
SET
  @AutoUpdateDefaultInView_d7563b80 = 1
SET
  @AutoUpdateCategory_d7563b80 = 1
SET
  @AutoUpdateDisplayName_d7563b80 = 1
SET
  @AutoUpdateIncludeInUserSearchAPI_d7563b80 = 1
SET
  @Encrypt_d7563b80 = 0
SET
  @AllowDecryptInAPI_d7563b80 = 0
SET
  @SendEncryptedValue_d7563b80 = 0
SET
  @IsSoftPrimaryKey_d7563b80 = 0
SET
  @IsSoftForeignKey_d7563b80 = 0
SET
  @JSONType_d7563b80 = N'IAccountingEngineExtensionConfiguration'
SET
  @JSONTypeIsArray_d7563b80 = 0
SET
  @JSONTypeDefinition_d7563b80 = N'/**
 * Host-tunable bag on AccountingEngineExtension.Configuration.
 *
 * Stored as JSON on `__mj_BizAppsAccounting.AccountingEngineExtension`.
 * CodeGen emits a typed `ConfigurationObject` accessor on the entity
 * returning `IAccountingEngineExtensionConfiguration | null`.
 *
 * Hook participation is NOT here — that lives on
 * `BaseAccountingEngineExtension` getters (`RunAfterSyncMasterData`, …)
 * and Before/After method overrides. This bag is host knobs only.
 *
 * Extension-specific keys may be present in the stored JSON; the owning
 * class documents them. They are not declared on this common interface.
 */
export interface IAccountingEngineExtensionConfiguration {
    /**
     * ISO date (YYYY-MM-DD) the extension should use when the engine did
     * not pass an as-of. NULL/omit = engine context (typically today UTC).
     */
    AsOf?: string | null;

    /**
     * When the triggering engine verb names objects (SyncMasterData), skip
     * this extension unless the intersection is non-empty. NULL/omit = always
     * run for a participating verb.
     */
    Objects?: Array<''accounts'' | ''dimensions'' | ''dimensionValues''> | null;

    /**
     * If true, a thrown extension does not fail the engine verb. Default
     * false — fail closed, matching the rest of the accounting engine.
     */
    ContinueOnError?: boolean | null;
}
'
SET
  @UserSearchPredicateAPI_d7563b80 = N'Contains'
SET
  @AutoUpdateUserSearchPredicate_d7563b80 = 1
SET
  @AutoUpdateFullTextSearch_d7563b80 = 1
SET
  @AutoUpdateExtendedType_d7563b80 = 1
SET
  @IsComputed_d7563b80 = 0
SET
  @ID_d7563b80 = 'E823D31F-B6BA-4858-8527-E42297B73645' EXEC [${mjSchema}].spUpdateEntityField @DisplayName = @DisplayName_d7563b80,
  @Description = @Description_d7563b80,
  @AutoUpdateDescription = @AutoUpdateDescription_d7563b80,
  @IsPrimaryKey = @IsPrimaryKey_d7563b80,
  @IsUnique = @IsUnique_d7563b80,
  @Category = @Category_d7563b80,
  @ValueListType = @ValueListType_d7563b80,
  @ExtendedType = @ExtendedType_d7563b80,
  @CodeType = @CodeType_d7563b80,
  @DefaultInView = @DefaultInView_d7563b80,
  @ViewCellTemplate = @ViewCellTemplate_d7563b80,
  @ViewCellTemplate_Clear = 1,
  @DefaultColumnWidth = @DefaultColumnWidth_d7563b80,
  @AllowUpdateAPI = @AllowUpdateAPI_d7563b80,
  @AllowUpdateInView = @AllowUpdateInView_d7563b80,
  @IncludeInUserSearchAPI = @IncludeInUserSearchAPI_d7563b80,
  @FullTextSearchEnabled = @FullTextSearchEnabled_d7563b80,
  @UserSearchParamFormatAPI = @UserSearchParamFormatAPI_d7563b80,
  @UserSearchParamFormatAPI_Clear = 1,
  @IncludeInGeneratedForm = @IncludeInGeneratedForm_d7563b80,
  @GeneratedFormSection = @GeneratedFormSection_d7563b80,
  @IsNameField = @IsNameField_d7563b80,
  @RelatedEntityID = @RelatedEntityID_d7563b80,
  @RelatedEntityID_Clear = 1,
  @RelatedEntityFieldName = @RelatedEntityFieldName_d7563b80,
  @RelatedEntityFieldName_Clear = 1,
  @IncludeRelatedEntityNameFieldInBaseView = @IncludeRelatedEntityNameFieldInBaseView_d7563b80,
  @RelatedEntityNameFieldMap = @RelatedEntityNameFieldMap_d7563b80,
  @RelatedEntityNameFieldMap_Clear = 1,
  @RelatedEntityDisplayType = @RelatedEntityDisplayType_d7563b80,
  @EntityIDFieldName = @EntityIDFieldName_d7563b80,
  @EntityIDFieldName_Clear = 1,
  @ScopeDefault = @ScopeDefault_d7563b80,
  @ScopeDefault_Clear = 1,
  @AutoUpdateRelatedEntityInfo = @AutoUpdateRelatedEntityInfo_d7563b80,
  @ValuesToPackWithSchema = @ValuesToPackWithSchema_d7563b80,
  @Status = @Status_d7563b80,
  @AutoUpdateIsNameField = @AutoUpdateIsNameField_d7563b80,
  @AutoUpdateDefaultInView = @AutoUpdateDefaultInView_d7563b80,
  @AutoUpdateCategory = @AutoUpdateCategory_d7563b80,
  @AutoUpdateDisplayName = @AutoUpdateDisplayName_d7563b80,
  @AutoUpdateIncludeInUserSearchAPI = @AutoUpdateIncludeInUserSearchAPI_d7563b80,
  @Encrypt = @Encrypt_d7563b80,
  @EncryptionKeyID = @EncryptionKeyID_d7563b80,
  @EncryptionKeyID_Clear = 1,
  @AllowDecryptInAPI = @AllowDecryptInAPI_d7563b80,
  @SendEncryptedValue = @SendEncryptedValue_d7563b80,
  @IsSoftPrimaryKey = @IsSoftPrimaryKey_d7563b80,
  @IsSoftForeignKey = @IsSoftForeignKey_d7563b80,
  @RelatedEntityJoinFields = @RelatedEntityJoinFields_d7563b80,
  @RelatedEntityJoinFields_Clear = 1,
  @JSONType = @JSONType_d7563b80,
  @JSONTypeIsArray = @JSONTypeIsArray_d7563b80,
  @JSONTypeDefinition = @JSONTypeDefinition_d7563b80,
  @UserSearchPredicateAPI = @UserSearchPredicateAPI_d7563b80,
  @AutoUpdateUserSearchPredicate = @AutoUpdateUserSearchPredicate_d7563b80,
  @AutoUpdateFullTextSearch = @AutoUpdateFullTextSearch_d7563b80,
  @AutoUpdateExtendedType = @AutoUpdateExtendedType_d7563b80,
  @IsComputed = @IsComputed_d7563b80,
  @EmbeddedRecord = @EmbeddedRecord_d7563b80,
  @EmbeddedRecord_Clear = 1,
  @Configuration = @Configuration_d7563b80,
  @Configuration_Clear = 1,
  @ID = @ID_d7563b80;

GO

-- Save MJ: Action Categories (core SP call only)
DECLARE @ID_a97ce412 UNIQUEIDENTIFIER,
@Name_a97ce412 NVARCHAR(255),
@Description_a97ce412 NVARCHAR(MAX),
@ParentID_a97ce412 UNIQUEIDENTIFIER,
@Status_a97ce412 NVARCHAR(20)
SET
  @ID_a97ce412 = '074DF299-8D1F-438B-B855-8DFF17AE565E'
SET
  @Name_a97ce412 = N'Accounting'
SET
  @Description_a97ce412 = N'Actions for BizApps Accounting subledger, journal entries, posting batches, and chart of accounts.'
SET
  @Status_a97ce412 = N'Active' EXEC [${mjSchema}].spCreateActionCategory @ID = @ID_a97ce412,
  @Name = @Name_a97ce412,
  @Description = @Description_a97ce412,
  @ParentID = @ParentID_a97ce412,
  @ParentID_Clear = 1,
  @Status = @Status_a97ce412;

GO

-- Save MJ: Actions (core SP call only)
DECLARE @ID_32bf56c4 UNIQUEIDENTIFIER,
@CategoryID_32bf56c4 UNIQUEIDENTIFIER,
@Name_32bf56c4 NVARCHAR(425),
@Description_32bf56c4 NVARCHAR(MAX),
@Type_32bf56c4 NVARCHAR(20),
@UserPrompt_32bf56c4 NVARCHAR(MAX),
@UserComments_32bf56c4 NVARCHAR(MAX),
@Code_32bf56c4 NVARCHAR(MAX),
@CodeComments_32bf56c4 NVARCHAR(MAX),
@CodeApprovalStatus_32bf56c4 NVARCHAR(20),
@CodeApprovalComments_32bf56c4 NVARCHAR(MAX),
@CodeApprovedByUserID_32bf56c4 UNIQUEIDENTIFIER,
@CodeApprovedAt_32bf56c4 DATETIMEOFFSET,
@CodeLocked_32bf56c4 BIT,
@ForceCodeGeneration_32bf56c4 BIT,
@RetentionPeriod_32bf56c4 INT,
@Status_32bf56c4 NVARCHAR(20),
@DriverClass_32bf56c4 NVARCHAR(255),
@ParentID_32bf56c4 UNIQUEIDENTIFIER,
@IconClass_32bf56c4 NVARCHAR(100),
@DefaultCompactPromptID_32bf56c4 UNIQUEIDENTIFIER,
@Config_32bf56c4 NVARCHAR(MAX),
@RuntimeActionConfiguration_32bf56c4 NVARCHAR(MAX),
@MaxExecutionTimeMS_32bf56c4 INT,
@CreatedByAgentID_32bf56c4 UNIQUEIDENTIFIER
SET
  @ID_32bf56c4 = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @CategoryID_32bf56c4 = '31C7433E-F36B-1410-8DB6-00021F8B792E'
SET
  @Name_32bf56c4 = N'Build Journal Entry Batches'
SET
  @Description_32bf56c4 = N'Builds single-company GL posting batches from pending candidate journal entries, netting lines per account/dimension combination. Supports filtering by target ERP system, cutoff date, and including/excluding specific JournalEntryType codes (such as excluding RevenueRecognition for daily batch runs).'
SET
  @Type_32bf56c4 = N'Custom'
SET
  @UserPrompt_32bf56c4 = N'Build GL posting batches for pending journal entries.'
SET
  @CodeApprovalStatus_32bf56c4 = N'Approved'
SET
  @CodeLocked_32bf56c4 = 0
SET
  @ForceCodeGeneration_32bf56c4 = 0
SET
  @Status_32bf56c4 = N'Active'
SET
  @DriverClass_32bf56c4 = N'Accounting.BuildJournalEntryBatches'
SET
  @IconClass_32bf56c4 = N'fa-solid fa-layer-group' EXEC [${mjSchema}].spCreateAction @ID = @ID_32bf56c4,
  @CategoryID = @CategoryID_32bf56c4,
  @Name = @Name_32bf56c4,
  @Description = @Description_32bf56c4,
  @Type = @Type_32bf56c4,
  @UserPrompt = @UserPrompt_32bf56c4,
  @UserComments = @UserComments_32bf56c4,
  @UserComments_Clear = 1,
  @Code = @Code_32bf56c4,
  @Code_Clear = 1,
  @CodeComments = @CodeComments_32bf56c4,
  @CodeComments_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_32bf56c4,
  @CodeApprovalComments = @CodeApprovalComments_32bf56c4,
  @CodeApprovalComments_Clear = 1,
  @CodeApprovedByUserID = @CodeApprovedByUserID_32bf56c4,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_32bf56c4,
  @CodeApprovedAt_Clear = 1,
  @CodeLocked = @CodeLocked_32bf56c4,
  @ForceCodeGeneration = @ForceCodeGeneration_32bf56c4,
  @RetentionPeriod = @RetentionPeriod_32bf56c4,
  @RetentionPeriod_Clear = 1,
  @Status = @Status_32bf56c4,
  @DriverClass = @DriverClass_32bf56c4,
  @ParentID = @ParentID_32bf56c4,
  @ParentID_Clear = 1,
  @IconClass = @IconClass_32bf56c4,
  @DefaultCompactPromptID = @DefaultCompactPromptID_32bf56c4,
  @DefaultCompactPromptID_Clear = 1,
  @Config = @Config_32bf56c4,
  @Config_Clear = 1,
  @RuntimeActionConfiguration = @RuntimeActionConfiguration_32bf56c4,
  @RuntimeActionConfiguration_Clear = 1,
  @MaxExecutionTimeMS = @MaxExecutionTimeMS_32bf56c4,
  @MaxExecutionTimeMS_Clear = 1,
  @CreatedByAgentID = @CreatedByAgentID_32bf56c4,
  @CreatedByAgentID_Clear = 1;

GO

-- Save MJ: Actions (core SP call only)
DECLARE @ID_883f32b3 UNIQUEIDENTIFIER,
@CategoryID_883f32b3 UNIQUEIDENTIFIER,
@Name_883f32b3 NVARCHAR(425),
@Description_883f32b3 NVARCHAR(MAX),
@Type_883f32b3 NVARCHAR(20),
@UserPrompt_883f32b3 NVARCHAR(MAX),
@UserComments_883f32b3 NVARCHAR(MAX),
@Code_883f32b3 NVARCHAR(MAX),
@CodeComments_883f32b3 NVARCHAR(MAX),
@CodeApprovalStatus_883f32b3 NVARCHAR(20),
@CodeApprovalComments_883f32b3 NVARCHAR(MAX),
@CodeApprovedByUserID_883f32b3 UNIQUEIDENTIFIER,
@CodeApprovedAt_883f32b3 DATETIMEOFFSET,
@CodeLocked_883f32b3 BIT,
@ForceCodeGeneration_883f32b3 BIT,
@RetentionPeriod_883f32b3 INT,
@Status_883f32b3 NVARCHAR(20),
@DriverClass_883f32b3 NVARCHAR(255),
@ParentID_883f32b3 UNIQUEIDENTIFIER,
@IconClass_883f32b3 NVARCHAR(100),
@DefaultCompactPromptID_883f32b3 UNIQUEIDENTIFIER,
@Config_883f32b3 NVARCHAR(MAX),
@RuntimeActionConfiguration_883f32b3 NVARCHAR(MAX),
@MaxExecutionTimeMS_883f32b3 INT,
@CreatedByAgentID_883f32b3 UNIQUEIDENTIFIER
SET
  @ID_883f32b3 = 'A839FB12-5813-4B85-8022-DF8943729BA2'
SET
  @CategoryID_883f32b3 = '31C7433E-F36B-1410-8DB6-00021F8B792E'
SET
  @Name_883f32b3 = N'Run ERP Sync'
SET
  @Description_883f32b3 = N'Pulls chart of accounts, dimensions, and dimension values from every credentialed Company Integration via AccountingERPEngine.SyncMasterData. One job, all companies. Hosts disable the scheduled job rather than deleting this action.'
SET
  @Type_883f32b3 = N'Custom'
SET
  @UserPrompt_883f32b3 = N'Sync ERP master data for accounting.'
SET
  @CodeApprovalStatus_883f32b3 = N'Approved'
SET
  @CodeLocked_883f32b3 = 0
SET
  @ForceCodeGeneration_883f32b3 = 0
SET
  @Status_883f32b3 = N'Active'
SET
  @DriverClass_883f32b3 = N'Accounting.RunERPSync'
SET
  @IconClass_883f32b3 = N'fa-solid fa-cloud-arrow-down' EXEC [${mjSchema}].spCreateAction @ID = @ID_883f32b3,
  @CategoryID = @CategoryID_883f32b3,
  @Name = @Name_883f32b3,
  @Description = @Description_883f32b3,
  @Type = @Type_883f32b3,
  @UserPrompt = @UserPrompt_883f32b3,
  @UserComments = @UserComments_883f32b3,
  @UserComments_Clear = 1,
  @Code = @Code_883f32b3,
  @Code_Clear = 1,
  @CodeComments = @CodeComments_883f32b3,
  @CodeComments_Clear = 1,
  @CodeApprovalStatus = @CodeApprovalStatus_883f32b3,
  @CodeApprovalComments = @CodeApprovalComments_883f32b3,
  @CodeApprovalComments_Clear = 1,
  @CodeApprovedByUserID = @CodeApprovedByUserID_883f32b3,
  @CodeApprovedByUserID_Clear = 1,
  @CodeApprovedAt = @CodeApprovedAt_883f32b3,
  @CodeApprovedAt_Clear = 1,
  @CodeLocked = @CodeLocked_883f32b3,
  @ForceCodeGeneration = @ForceCodeGeneration_883f32b3,
  @RetentionPeriod = @RetentionPeriod_883f32b3,
  @RetentionPeriod_Clear = 1,
  @Status = @Status_883f32b3,
  @DriverClass = @DriverClass_883f32b3,
  @ParentID = @ParentID_883f32b3,
  @ParentID_Clear = 1,
  @IconClass = @IconClass_883f32b3,
  @DefaultCompactPromptID = @DefaultCompactPromptID_883f32b3,
  @DefaultCompactPromptID_Clear = 1,
  @Config = @Config_883f32b3,
  @Config_Clear = 1,
  @RuntimeActionConfiguration = @RuntimeActionConfiguration_883f32b3,
  @RuntimeActionConfiguration_Clear = 1,
  @MaxExecutionTimeMS = @MaxExecutionTimeMS_883f32b3,
  @MaxExecutionTimeMS_Clear = 1,
  @CreatedByAgentID = @CreatedByAgentID_883f32b3,
  @CreatedByAgentID_Clear = 1;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_de0b37cc UNIQUEIDENTIFIER,
@ActionID_de0b37cc UNIQUEIDENTIFIER,
@Name_de0b37cc NVARCHAR(255),
@DefaultValue_de0b37cc NVARCHAR(MAX),
@Type_de0b37cc NCHAR(10),
@ValueType_de0b37cc NVARCHAR(30),
@IsArray_de0b37cc BIT,
@Description_de0b37cc NVARCHAR(MAX),
@IsRequired_de0b37cc BIT,
@MediaModality_de0b37cc NVARCHAR(20),
@LogValue_de0b37cc BIT
SET
  @ID_de0b37cc = '8A52D539-7431-4F29-873D-88229F5CDA01'
SET
  @ActionID_de0b37cc = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_de0b37cc = N'TargetSystem'
SET
  @Type_de0b37cc = N'Input'
SET
  @ValueType_de0b37cc = N'Scalar'
SET
  @IsArray_de0b37cc = 0
SET
  @Description_de0b37cc = N'The ERP target system to stamp on built batches (e.g. ''BusinessCentral'', ''QuickBooks'', ''NetSuite'', ''Sage'', ''Xero'', ''Other''). Defaults to ''BusinessCentral''.'
SET
  @IsRequired_de0b37cc = 0
SET
  @LogValue_de0b37cc = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_de0b37cc,
  @ActionID = @ActionID_de0b37cc,
  @Name = @Name_de0b37cc,
  @DefaultValue = @DefaultValue_de0b37cc,
  @DefaultValue_Clear = 1,
  @Type = @Type_de0b37cc,
  @ValueType = @ValueType_de0b37cc,
  @IsArray = @IsArray_de0b37cc,
  @Description = @Description_de0b37cc,
  @IsRequired = @IsRequired_de0b37cc,
  @MediaModality = @MediaModality_de0b37cc,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_de0b37cc;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_04e1ef0d UNIQUEIDENTIFIER,
@ActionID_04e1ef0d UNIQUEIDENTIFIER,
@Name_04e1ef0d NVARCHAR(255),
@DefaultValue_04e1ef0d NVARCHAR(MAX),
@Type_04e1ef0d NCHAR(10),
@ValueType_04e1ef0d NVARCHAR(30),
@IsArray_04e1ef0d BIT,
@Description_04e1ef0d NVARCHAR(MAX),
@IsRequired_04e1ef0d BIT,
@MediaModality_04e1ef0d NVARCHAR(20),
@LogValue_04e1ef0d BIT
SET
  @ID_04e1ef0d = '9B2735DE-AC19-49BC-8496-DA35B80C1402'
SET
  @ActionID_04e1ef0d = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_04e1ef0d = N'Cutoff'
SET
  @Type_04e1ef0d = N'Input'
SET
  @ValueType_04e1ef0d = N'Scalar'
SET
  @IsArray_04e1ef0d = 0
SET
  @Description_04e1ef0d = N'ISO date cutoff (e.g. ''2026-08-25''). Entries on or before this date will be gathered.'
SET
  @IsRequired_04e1ef0d = 0
SET
  @LogValue_04e1ef0d = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_04e1ef0d,
  @ActionID = @ActionID_04e1ef0d,
  @Name = @Name_04e1ef0d,
  @DefaultValue = @DefaultValue_04e1ef0d,
  @DefaultValue_Clear = 1,
  @Type = @Type_04e1ef0d,
  @ValueType = @ValueType_04e1ef0d,
  @IsArray = @IsArray_04e1ef0d,
  @Description = @Description_04e1ef0d,
  @IsRequired = @IsRequired_04e1ef0d,
  @MediaModality = @MediaModality_04e1ef0d,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_04e1ef0d;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_042a8418 UNIQUEIDENTIFIER,
@ActionID_042a8418 UNIQUEIDENTIFIER,
@Name_042a8418 NVARCHAR(255),
@DefaultValue_042a8418 NVARCHAR(MAX),
@Type_042a8418 NCHAR(10),
@ValueType_042a8418 NVARCHAR(30),
@IsArray_042a8418 BIT,
@Description_042a8418 NVARCHAR(MAX),
@IsRequired_042a8418 BIT,
@MediaModality_042a8418 NVARCHAR(20),
@LogValue_042a8418 BIT
SET
  @ID_042a8418 = '2C4F1B3E-7284-482F-B059-7CD839AE9803'
SET
  @ActionID_042a8418 = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_042a8418 = N'StartDate'
SET
  @Type_042a8418 = N'Input'
SET
  @ValueType_042a8418 = N'Scalar'
SET
  @IsArray_042a8418 = 0
SET
  @Description_042a8418 = N'Optional ISO start date lower bound for candidate entries.'
SET
  @IsRequired_042a8418 = 0
SET
  @LogValue_042a8418 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_042a8418,
  @ActionID = @ActionID_042a8418,
  @Name = @Name_042a8418,
  @DefaultValue = @DefaultValue_042a8418,
  @DefaultValue_Clear = 1,
  @Type = @Type_042a8418,
  @ValueType = @ValueType_042a8418,
  @IsArray = @IsArray_042a8418,
  @Description = @Description_042a8418,
  @IsRequired = @IsRequired_042a8418,
  @MediaModality = @MediaModality_042a8418,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_042a8418;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_172e620f UNIQUEIDENTIFIER,
@ActionID_172e620f UNIQUEIDENTIFIER,
@Name_172e620f NVARCHAR(255),
@DefaultValue_172e620f NVARCHAR(MAX),
@Type_172e620f NCHAR(10),
@ValueType_172e620f NVARCHAR(30),
@IsArray_172e620f BIT,
@Description_172e620f NVARCHAR(MAX),
@IsRequired_172e620f BIT,
@MediaModality_172e620f NVARCHAR(20),
@LogValue_172e620f BIT
SET
  @ID_172e620f = '7E94BC01-B341-45DF-9824-34FD8A110904'
SET
  @ActionID_172e620f = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_172e620f = N'ExcludeEntryTypeCodes'
SET
  @Type_172e620f = N'Input'
SET
  @ValueType_172e620f = N'Scalar'
SET
  @IsArray_172e620f = 1
SET
  @Description_172e620f = N'JournalEntryType codes to EXCLUDE from the candidate pool (e.g. [''RevenueRecognition''] for daily operational batches).'
SET
  @IsRequired_172e620f = 0
SET
  @LogValue_172e620f = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_172e620f,
  @ActionID = @ActionID_172e620f,
  @Name = @Name_172e620f,
  @DefaultValue = @DefaultValue_172e620f,
  @DefaultValue_Clear = 1,
  @Type = @Type_172e620f,
  @ValueType = @ValueType_172e620f,
  @IsArray = @IsArray_172e620f,
  @Description = @Description_172e620f,
  @IsRequired = @IsRequired_172e620f,
  @MediaModality = @MediaModality_172e620f,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_172e620f;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_34f8fff1 UNIQUEIDENTIFIER,
@ActionID_34f8fff1 UNIQUEIDENTIFIER,
@Name_34f8fff1 NVARCHAR(255),
@DefaultValue_34f8fff1 NVARCHAR(MAX),
@Type_34f8fff1 NCHAR(10),
@ValueType_34f8fff1 NVARCHAR(30),
@IsArray_34f8fff1 BIT,
@Description_34f8fff1 NVARCHAR(MAX),
@IsRequired_34f8fff1 BIT,
@MediaModality_34f8fff1 NVARCHAR(20),
@LogValue_34f8fff1 BIT
SET
  @ID_34f8fff1 = '5F89AA32-1594-47CA-8AC4-66E875CD2105'
SET
  @ActionID_34f8fff1 = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_34f8fff1 = N'EntryTypeCodes'
SET
  @Type_34f8fff1 = N'Input'
SET
  @ValueType_34f8fff1 = N'Scalar'
SET
  @IsArray_34f8fff1 = 1
SET
  @Description_34f8fff1 = N'Optional whitelist of JournalEntryType codes to include.'
SET
  @IsRequired_34f8fff1 = 0
SET
  @LogValue_34f8fff1 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_34f8fff1,
  @ActionID = @ActionID_34f8fff1,
  @Name = @Name_34f8fff1,
  @DefaultValue = @DefaultValue_34f8fff1,
  @DefaultValue_Clear = 1,
  @Type = @Type_34f8fff1,
  @ValueType = @ValueType_34f8fff1,
  @IsArray = @IsArray_34f8fff1,
  @Description = @Description_34f8fff1,
  @IsRequired = @IsRequired_34f8fff1,
  @MediaModality = @MediaModality_34f8fff1,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_34f8fff1;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_dfc3c250 UNIQUEIDENTIFIER,
@ActionID_dfc3c250 UNIQUEIDENTIFIER,
@Name_dfc3c250 NVARCHAR(255),
@DefaultValue_dfc3c250 NVARCHAR(MAX),
@Type_dfc3c250 NCHAR(10),
@ValueType_dfc3c250 NVARCHAR(30),
@IsArray_dfc3c250 BIT,
@Description_dfc3c250 NVARCHAR(MAX),
@IsRequired_dfc3c250 BIT,
@MediaModality_dfc3c250 NVARCHAR(20),
@LogValue_dfc3c250 BIT
SET
  @ID_dfc3c250 = '3CD124AB-9A52-4752-94C0-4822B1489006'
SET
  @ActionID_dfc3c250 = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_dfc3c250 = N'CompanyIDs'
SET
  @Type_dfc3c250 = N'Input'
SET
  @ValueType_dfc3c250 = N'Scalar'
SET
  @IsArray_dfc3c250 = 1
SET
  @Description_dfc3c250 = N'Optional list of Company IDs to restrict batch building to.'
SET
  @IsRequired_dfc3c250 = 0
SET
  @LogValue_dfc3c250 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_dfc3c250,
  @ActionID = @ActionID_dfc3c250,
  @Name = @Name_dfc3c250,
  @DefaultValue = @DefaultValue_dfc3c250,
  @DefaultValue_Clear = 1,
  @Type = @Type_dfc3c250,
  @ValueType = @ValueType_dfc3c250,
  @IsArray = @IsArray_dfc3c250,
  @Description = @Description_dfc3c250,
  @IsRequired = @IsRequired_dfc3c250,
  @MediaModality = @MediaModality_dfc3c250,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_dfc3c250;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_5c8aaef6 UNIQUEIDENTIFIER,
@ActionID_5c8aaef6 UNIQUEIDENTIFIER,
@Name_5c8aaef6 NVARCHAR(255),
@DefaultValue_5c8aaef6 NVARCHAR(MAX),
@Type_5c8aaef6 NCHAR(10),
@ValueType_5c8aaef6 NVARCHAR(30),
@IsArray_5c8aaef6 BIT,
@Description_5c8aaef6 NVARCHAR(MAX),
@IsRequired_5c8aaef6 BIT,
@MediaModality_5c8aaef6 NVARCHAR(20),
@LogValue_5c8aaef6 BIT
SET
  @ID_5c8aaef6 = '1738AB44-013D-47C5-8592-AE91B248CD07'
SET
  @ActionID_5c8aaef6 = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_5c8aaef6 = N'BatchCount'
SET
  @Type_5c8aaef6 = N'Output'
SET
  @ValueType_5c8aaef6 = N'Scalar'
SET
  @IsArray_5c8aaef6 = 0
SET
  @Description_5c8aaef6 = N'The number of batches created.'
SET
  @IsRequired_5c8aaef6 = 0
SET
  @LogValue_5c8aaef6 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_5c8aaef6,
  @ActionID = @ActionID_5c8aaef6,
  @Name = @Name_5c8aaef6,
  @DefaultValue = @DefaultValue_5c8aaef6,
  @DefaultValue_Clear = 1,
  @Type = @Type_5c8aaef6,
  @ValueType = @ValueType_5c8aaef6,
  @IsArray = @IsArray_5c8aaef6,
  @Description = @Description_5c8aaef6,
  @IsRequired = @IsRequired_5c8aaef6,
  @MediaModality = @MediaModality_5c8aaef6,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_5c8aaef6;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_471cc9bf UNIQUEIDENTIFIER,
@ActionID_471cc9bf UNIQUEIDENTIFIER,
@Name_471cc9bf NVARCHAR(255),
@DefaultValue_471cc9bf NVARCHAR(MAX),
@Type_471cc9bf NCHAR(10),
@ValueType_471cc9bf NVARCHAR(30),
@IsArray_471cc9bf BIT,
@Description_471cc9bf NVARCHAR(MAX),
@IsRequired_471cc9bf BIT,
@MediaModality_471cc9bf NVARCHAR(20),
@LogValue_471cc9bf BIT
SET
  @ID_471cc9bf = '2837AC55-124E-48D6-96A3-BF02C359DE08'
SET
  @ActionID_471cc9bf = 'E839FB12-5813-4B85-8022-DF8943729BA1'
SET
  @Name_471cc9bf = N'Batches'
SET
  @Type_471cc9bf = N'Output'
SET
  @ValueType_471cc9bf = N'Scalar'
SET
  @IsArray_471cc9bf = 0
SET
  @Description_471cc9bf = N'JSON array of created batch details.'
SET
  @IsRequired_471cc9bf = 0
SET
  @LogValue_471cc9bf = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_471cc9bf,
  @ActionID = @ActionID_471cc9bf,
  @Name = @Name_471cc9bf,
  @DefaultValue = @DefaultValue_471cc9bf,
  @DefaultValue_Clear = 1,
  @Type = @Type_471cc9bf,
  @ValueType = @ValueType_471cc9bf,
  @IsArray = @IsArray_471cc9bf,
  @Description = @Description_471cc9bf,
  @IsRequired = @IsRequired_471cc9bf,
  @MediaModality = @MediaModality_471cc9bf,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_471cc9bf;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_8c3318e2 UNIQUEIDENTIFIER,
@ActionID_8c3318e2 UNIQUEIDENTIFIER,
@Name_8c3318e2 NVARCHAR(255),
@DefaultValue_8c3318e2 NVARCHAR(MAX),
@Type_8c3318e2 NCHAR(10),
@ValueType_8c3318e2 NVARCHAR(30),
@IsArray_8c3318e2 BIT,
@Description_8c3318e2 NVARCHAR(MAX),
@IsRequired_8c3318e2 BIT,
@MediaModality_8c3318e2 NVARCHAR(20),
@LogValue_8c3318e2 BIT
SET
  @ID_8c3318e2 = 'A839FB12-5813-4B85-8022-DF8943729BB1'
SET
  @ActionID_8c3318e2 = 'A839FB12-5813-4B85-8022-DF8943729BA2'
SET
  @Name_8c3318e2 = N'Objects'
SET
  @Type_8c3318e2 = N'Input'
SET
  @ValueType_8c3318e2 = N'Scalar'
SET
  @IsArray_8c3318e2 = 1
SET
  @Description_8c3318e2 = N'Subset of accounts | dimensions | dimensionValues. Omit for all three.'
SET
  @IsRequired_8c3318e2 = 0
SET
  @LogValue_8c3318e2 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_8c3318e2,
  @ActionID = @ActionID_8c3318e2,
  @Name = @Name_8c3318e2,
  @DefaultValue = @DefaultValue_8c3318e2,
  @DefaultValue_Clear = 1,
  @Type = @Type_8c3318e2,
  @ValueType = @ValueType_8c3318e2,
  @IsArray = @IsArray_8c3318e2,
  @Description = @Description_8c3318e2,
  @IsRequired = @IsRequired_8c3318e2,
  @MediaModality = @MediaModality_8c3318e2,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_8c3318e2;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_dfdd2a43 UNIQUEIDENTIFIER,
@ActionID_dfdd2a43 UNIQUEIDENTIFIER,
@Name_dfdd2a43 NVARCHAR(255),
@DefaultValue_dfdd2a43 NVARCHAR(MAX),
@Type_dfdd2a43 NCHAR(10),
@ValueType_dfdd2a43 NVARCHAR(30),
@IsArray_dfdd2a43 BIT,
@Description_dfdd2a43 NVARCHAR(MAX),
@IsRequired_dfdd2a43 BIT,
@MediaModality_dfdd2a43 NVARCHAR(20),
@LogValue_dfdd2a43 BIT
SET
  @ID_dfdd2a43 = 'A839FB12-5813-4B85-8022-DF8943729BB2'
SET
  @ActionID_dfdd2a43 = 'A839FB12-5813-4B85-8022-DF8943729BA2'
SET
  @Name_dfdd2a43 = N'CompanyIDs'
SET
  @Type_dfdd2a43 = N'Input'
SET
  @ValueType_dfdd2a43 = N'Scalar'
SET
  @IsArray_dfdd2a43 = 1
SET
  @Description_dfdd2a43 = N'Optional company filter. Omit for every credentialed company.'
SET
  @IsRequired_dfdd2a43 = 0
SET
  @LogValue_dfdd2a43 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_dfdd2a43,
  @ActionID = @ActionID_dfdd2a43,
  @Name = @Name_dfdd2a43,
  @DefaultValue = @DefaultValue_dfdd2a43,
  @DefaultValue_Clear = 1,
  @Type = @Type_dfdd2a43,
  @ValueType = @ValueType_dfdd2a43,
  @IsArray = @IsArray_dfdd2a43,
  @Description = @Description_dfdd2a43,
  @IsRequired = @IsRequired_dfdd2a43,
  @MediaModality = @MediaModality_dfdd2a43,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_dfdd2a43;

GO

-- Save MJ: Action Params (core SP call only)
DECLARE @ID_a3fe7432 UNIQUEIDENTIFIER,
@ActionID_a3fe7432 UNIQUEIDENTIFIER,
@Name_a3fe7432 NVARCHAR(255),
@DefaultValue_a3fe7432 NVARCHAR(MAX),
@Type_a3fe7432 NCHAR(10),
@ValueType_a3fe7432 NVARCHAR(30),
@IsArray_a3fe7432 BIT,
@Description_a3fe7432 NVARCHAR(MAX),
@IsRequired_a3fe7432 BIT,
@MediaModality_a3fe7432 NVARCHAR(20),
@LogValue_a3fe7432 BIT
SET
  @ID_a3fe7432 = 'A839FB12-5813-4B85-8022-DF8943729BB3'
SET
  @ActionID_a3fe7432 = 'A839FB12-5813-4B85-8022-DF8943729BA2'
SET
  @Name_a3fe7432 = N'Results'
SET
  @Type_a3fe7432 = N'Output'
SET
  @ValueType_a3fe7432 = N'Scalar'
SET
  @IsArray_a3fe7432 = 0
SET
  @Description_a3fe7432 = N'Per-company sync results.'
SET
  @IsRequired_a3fe7432 = 0
SET
  @LogValue_a3fe7432 = 1
EXEC [${mjSchema}].spCreateActionParam @ID = @ID_a3fe7432,
  @ActionID = @ActionID_a3fe7432,
  @Name = @Name_a3fe7432,
  @DefaultValue = @DefaultValue_a3fe7432,
  @DefaultValue_Clear = 1,
  @Type = @Type_a3fe7432,
  @ValueType = @ValueType_a3fe7432,
  @IsArray = @IsArray_a3fe7432,
  @Description = @Description_a3fe7432,
  @IsRequired = @IsRequired_a3fe7432,
  @MediaModality = @MediaModality_a3fe7432,
  @MediaModality_Clear = 1,
  @LogValue = @LogValue_a3fe7432;

GO

-- Save MJ: Entity Relationships (core SP call only)
DECLARE @EntityID_ba2c390d UNIQUEIDENTIFIER,
@Sequence_ba2c390d INT,
@RelatedEntityID_ba2c390d UNIQUEIDENTIFIER,
@BundleInAPI_ba2c390d BIT,
@IncludeInParentAllQuery_ba2c390d BIT,
@Type_ba2c390d NCHAR(20),
@EntityKeyField_ba2c390d NVARCHAR(255),
@RelatedEntityJoinField_ba2c390d NVARCHAR(255),
@JoinView_ba2c390d NVARCHAR(255),
@JoinEntityJoinField_ba2c390d NVARCHAR(255),
@JoinEntityInverseJoinField_ba2c390d NVARCHAR(255),
@DisplayInForm_ba2c390d BIT,
@DisplayLocation_ba2c390d NVARCHAR(50),
@DisplayName_ba2c390d NVARCHAR(255),
@DisplayIconType_ba2c390d NVARCHAR(50),
@DisplayIcon_ba2c390d NVARCHAR(255),
@DisplayComponentID_ba2c390d UNIQUEIDENTIFIER,
@DisplayComponentConfiguration_ba2c390d NVARCHAR(MAX),
@AutoUpdateFromSchema_ba2c390d BIT,
@AdditionalFieldsToInclude_ba2c390d NVARCHAR(MAX),
@AutoUpdateAdditionalFieldsToInclude_ba2c390d BIT,
@RelatedRecordCollection_ba2c390d NVARCHAR(MAX),
@Configuration_ba2c390d NVARCHAR(MAX),
@ID_ba2c390d UNIQUEIDENTIFIER
SET
  @EntityID_ba2c390d = 'B348FFA2-B1A7-4AC2-B6FD-F4E0C0697466'
SET
  @Sequence_ba2c390d = 11
SET
  @RelatedEntityID_ba2c390d = '87AD37E9-62F9-4F0E-A15B-F64ADF009112'
SET
  @BundleInAPI_ba2c390d = 1
SET
  @IncludeInParentAllQuery_ba2c390d = 0
SET
  @Type_ba2c390d = N'One To Many'
SET
  @RelatedEntityJoinField_ba2c390d = N'ApprovalTaskID'
SET
  @DisplayInForm_ba2c390d = 1
SET
  @DisplayLocation_ba2c390d = N'After Field Tabs'
SET
  @DisplayName_ba2c390d = N'Journal Entry Batches'
SET
  @DisplayIconType_ba2c390d = N'Related Entity Icon'
SET
  @AutoUpdateFromSchema_ba2c390d = 1
SET
  @AutoUpdateAdditionalFieldsToInclude_ba2c390d = 1
SET
  @Configuration_ba2c390d = N'{
  "UI": {
    "inclusion": "More"
  }
}'
SET
  @ID_ba2c390d = '458A6983-D261-4245-949C-E5E9F4A40F10' EXEC [${mjSchema}].spUpdateEntityRelationship @EntityID = @EntityID_ba2c390d,
  @Sequence = @Sequence_ba2c390d,
  @RelatedEntityID = @RelatedEntityID_ba2c390d,
  @BundleInAPI = @BundleInAPI_ba2c390d,
  @IncludeInParentAllQuery = @IncludeInParentAllQuery_ba2c390d,
  @Type = @Type_ba2c390d,
  @EntityKeyField = @EntityKeyField_ba2c390d,
  @EntityKeyField_Clear = 1,
  @RelatedEntityJoinField = @RelatedEntityJoinField_ba2c390d,
  @JoinView = @JoinView_ba2c390d,
  @JoinView_Clear = 1,
  @JoinEntityJoinField = @JoinEntityJoinField_ba2c390d,
  @JoinEntityJoinField_Clear = 1,
  @JoinEntityInverseJoinField = @JoinEntityInverseJoinField_ba2c390d,
  @JoinEntityInverseJoinField_Clear = 1,
  @DisplayInForm = @DisplayInForm_ba2c390d,
  @DisplayLocation = @DisplayLocation_ba2c390d,
  @DisplayName = @DisplayName_ba2c390d,
  @DisplayIconType = @DisplayIconType_ba2c390d,
  @DisplayIcon = @DisplayIcon_ba2c390d,
  @DisplayIcon_Clear = 1,
  @DisplayComponentID = @DisplayComponentID_ba2c390d,
  @DisplayComponentID_Clear = 1,
  @DisplayComponentConfiguration = @DisplayComponentConfiguration_ba2c390d,
  @DisplayComponentConfiguration_Clear = 1,
  @AutoUpdateFromSchema = @AutoUpdateFromSchema_ba2c390d,
  @AdditionalFieldsToInclude = @AdditionalFieldsToInclude_ba2c390d,
  @AdditionalFieldsToInclude_Clear = 1,
  @AutoUpdateAdditionalFieldsToInclude = @AutoUpdateAdditionalFieldsToInclude_ba2c390d,
  @RelatedRecordCollection = @RelatedRecordCollection_ba2c390d,
  @RelatedRecordCollection_Clear = 1,
  @Configuration = @Configuration_ba2c390d,
  @ID = @ID_ba2c390d;

GO

-- Save MJ: Scheduled Jobs (core SP call only)
DECLARE @ID_b01c7f26 UNIQUEIDENTIFIER,
@JobTypeID_b01c7f26 UNIQUEIDENTIFIER,
@Name_b01c7f26 NVARCHAR(200),
@Description_b01c7f26 NVARCHAR(MAX),
@CronExpression_b01c7f26 NVARCHAR(120),
@Timezone_b01c7f26 NVARCHAR(64),
@StartAt_b01c7f26 DATETIMEOFFSET,
@EndAt_b01c7f26 DATETIMEOFFSET,
@Status_b01c7f26 NVARCHAR(20),
@Configuration_b01c7f26 NVARCHAR(MAX),
@OwnerUserID_b01c7f26 UNIQUEIDENTIFIER,
@LastRunAt_b01c7f26 DATETIMEOFFSET,
@NextRunAt_b01c7f26 DATETIMEOFFSET,
@RunCount_b01c7f26 INT,
@SuccessCount_b01c7f26 INT,
@FailureCount_b01c7f26 INT,
@NotifyOnSuccess_b01c7f26 BIT,
@NotifyOnFailure_b01c7f26 BIT,
@NotifyUserID_b01c7f26 UNIQUEIDENTIFIER,
@NotifyViaEmail_b01c7f26 BIT,
@NotifyViaInApp_b01c7f26 BIT,
@LockToken_b01c7f26 UNIQUEIDENTIFIER,
@LockedAt_b01c7f26 DATETIMEOFFSET,
@LockedByInstance_b01c7f26 NVARCHAR(255),
@ExpectedCompletionAt_b01c7f26 DATETIMEOFFSET,
@ConcurrencyMode_b01c7f26 NVARCHAR(20),
@RunImmediatelyIfNeverRun_b01c7f26 BIT,
@MaxRuntimeMinutes_b01c7f26 INT,
@MissedRunPolicy_b01c7f26 NVARCHAR(20)
SET
  @ID_b01c7f26 = 'C839FB12-5813-4B85-8022-DF8943729BA3'
SET
  @JobTypeID_b01c7f26 = '3B94DD43-E961-4D85-B7F4-B6783D748766'
SET
  @Name_b01c7f26 = N'Accounting — ERP master data (daily)'
SET
  @Description_b01c7f26 = N'Pulls chart of accounts, dimensions, and dimension values from every active Company Integration. Posts of journal batches are a separate engine verb, not this job.'
SET
  @CronExpression_b01c7f26 = N'0 0 2 * * *'
SET
  @Timezone_b01c7f26 = N'UTC'
SET
  @Status_b01c7f26 = N'Active'
SET
  @Configuration_b01c7f26 = N'{"ActionID":"A839FB12-5813-4B85-8022-DF8943729BA2"}'
SET
  @RunCount_b01c7f26 = 0
SET
  @SuccessCount_b01c7f26 = 0
SET
  @FailureCount_b01c7f26 = 0
SET
  @NotifyOnSuccess_b01c7f26 = 0
SET
  @NotifyOnFailure_b01c7f26 = 1
SET
  @NotifyViaEmail_b01c7f26 = 0
SET
  @NotifyViaInApp_b01c7f26 = 1
SET
  @ConcurrencyMode_b01c7f26 = N'Skip'
SET
  @RunImmediatelyIfNeverRun_b01c7f26 = 0
SET
  @MaxRuntimeMinutes_b01c7f26 = 60
SET
  @MissedRunPolicy_b01c7f26 = N'RunOnce' EXEC [${mjSchema}].spCreateScheduledJob @ID = @ID_b01c7f26,
  @JobTypeID = @JobTypeID_b01c7f26,
  @Name = @Name_b01c7f26,
  @Description = @Description_b01c7f26,
  @CronExpression = @CronExpression_b01c7f26,
  @Timezone = @Timezone_b01c7f26,
  @StartAt = @StartAt_b01c7f26,
  @StartAt_Clear = 1,
  @EndAt = @EndAt_b01c7f26,
  @EndAt_Clear = 1,
  @Status = @Status_b01c7f26,
  @Configuration = @Configuration_b01c7f26,
  @OwnerUserID = @OwnerUserID_b01c7f26,
  @OwnerUserID_Clear = 1,
  @LastRunAt = @LastRunAt_b01c7f26,
  @LastRunAt_Clear = 1,
  @NextRunAt = @NextRunAt_b01c7f26,
  @NextRunAt_Clear = 1,
  @RunCount = @RunCount_b01c7f26,
  @SuccessCount = @SuccessCount_b01c7f26,
  @FailureCount = @FailureCount_b01c7f26,
  @NotifyOnSuccess = @NotifyOnSuccess_b01c7f26,
  @NotifyOnFailure = @NotifyOnFailure_b01c7f26,
  @NotifyUserID = @NotifyUserID_b01c7f26,
  @NotifyUserID_Clear = 1,
  @NotifyViaEmail = @NotifyViaEmail_b01c7f26,
  @NotifyViaInApp = @NotifyViaInApp_b01c7f26,
  @LockToken = @LockToken_b01c7f26,
  @LockToken_Clear = 1,
  @LockedAt = @LockedAt_b01c7f26,
  @LockedAt_Clear = 1,
  @LockedByInstance = @LockedByInstance_b01c7f26,
  @LockedByInstance_Clear = 1,
  @ExpectedCompletionAt = @ExpectedCompletionAt_b01c7f26,
  @ExpectedCompletionAt_Clear = 1,
  @ConcurrencyMode = @ConcurrencyMode_b01c7f26,
  @RunImmediatelyIfNeverRun = @RunImmediatelyIfNeverRun_b01c7f26,
  @MaxRuntimeMinutes = @MaxRuntimeMinutes_b01c7f26,
  @MissedRunPolicy = @MissedRunPolicy_b01c7f26;

GO


-- End of SQL Logging Session
-- Session ID: 0a868c70-eb0f-4fcf-ab9c-0350fec6ff7c
-- Completed: 2026-09-02T04:41:42.235Z
-- Duration: 4096ms
-- Total Statements: 17
