-- =============================================================================================
-- BizApps Accounting v0.20.x -- Metadata_Sync (one per release)
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --ci` (MJ CLI 6.1.4) against a database built from
-- migrations ONLY: MJ core 6.1.4, bizapps-common v5.50.1, bizapps-tasks v1.6.2, then this app's
-- migrations at `next`. Push result: 9 created, 0 updated, 163 unchanged, 0 errors.
--
-- CREATED: Finance Exception Type ERP_POSTING_NOT_READ_BACK (ERP Posting Not Read Back), which the
-- 0.20 batch engine raises when the ERP accepts a journal batch that it cannot then read back.
--
-- NOT INCLUDED, as in 0.17: metadata/scheduled-jobs (the nightly Order & Payment posting and
-- monthly subscription recognition jobs are declared Active -- seeding them switches on ERP posting
-- on every host, which needs its own decision) and the ML bench output (ml-models,
-- ml-training-pipelines, ml-model-scoring-bindings, record-processes). Those are the other 8 creates.
--
-- TRANSFORMS: `EXEC [__mj_BizAppsAccounting]` -> `EXEC [${flyway:defaultSchema}]`; string values are
-- untouched. The create is guarded on ID OR Code. Idempotent.
-- =============================================================================================
-- Save MJ_BizApps_Accounting: Finance Exception Types (core SP call only)
DECLARE @ID_a4a14ee36a17 UNIQUEIDENTIFIER,
@Code_a4a14ee36a17 NVARCHAR(60),
@Name_a4a14ee36a17 NVARCHAR(100),
@Description_a4a14ee36a17 NVARCHAR(MAX),
@OwningApp_a4a14ee36a17 NVARCHAR(100),
@IsActive_a4a14ee36a17 BIT,
@Configuration_a4a14ee36a17 NVARCHAR(MAX)
SET
  @ID_a4a14ee36a17 = '4EAA070C-7A17-4181-A8AE-D6C5D8316C62'
SET
  @Code_a4a14ee36a17 = N'ERP_POSTING_NOT_READ_BACK'
SET
  @Name_a4a14ee36a17 = N'ERP Posting Not Read Back'
SET
  @Description_a4a14ee36a17 = N'A journal batch the ERP accepted that could not then be read back from the ERP, so the reference recorded on the batch may not be the ERP''s own number for it, and the ERP lookup may not see this company''s postings. While one is Open for a company, a Failed batch in that company whose ERP lookup finds nothing needs the operator''s confirmation before it is sent again or cancelled. Raised by accounting when a batch posts, against the batch.'
SET
  @OwningApp_a4a14ee36a17 = N'accounting'
SET
  @IsActive_a4a14ee36a17 = 1
SET
  @Configuration_a4a14ee36a17 = N'{}'
IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[FinanceExceptionType]
               WHERE [ID] = @ID_a4a14ee36a17
                  OR ([Code] = @Code_a4a14ee36a17))
EXEC [${flyway:defaultSchema}].spCreateFinanceExceptionType @ID = @ID_a4a14ee36a17,
  @Code = @Code_a4a14ee36a17,
  @Name = @Name_a4a14ee36a17,
  @Description = @Description_a4a14ee36a17,
  @OwningApp = @OwningApp_a4a14ee36a17,
  @IsActive = @IsActive_a4a14ee36a17,
  @Configuration = @Configuration_a4a14ee36a17;

GO
