-- =============================================================================================
-- BizApps Accounting v0.16.x -- Metadata_Sync: the Customer Deposits and Unbilled Receivable roles
-- =============================================================================================
-- Generated by `mj sync push --dir metadata --include gl-account-roles --ci` (MJ CLI 6.1.4)
-- against a database built from migrations ONLY: MJ core 6.1.4, bizapps-common v5.47.0,
-- bizapps-tasks v1.6.1, then this app's migrations at `next` (no unreleased seed held back).
-- Push result: 2 created, 0 updated, 10 unchanged, 0 errors.
--
-- WHY. Both roles exist only in metadata/gl-account-roles (Unbilled Receivable from #165,
-- Customer Deposits from #194); no migration has ever created them, so on a host the role row is
-- missing and the resolver finds nothing. bizapps-orders 5.20 needs both: it credits cash beyond
-- what is invoiced to Customer Deposits and refuses the payment when that role does not resolve
-- (PaymentAllocationFactory, RefuseUnlinkedCustomerDeposits), and it posts percentage-of-
-- completion catch-up beyond the deferred balance to Unbilled Receivable. Finance cannot link an
-- account to a role that is not there. Orders raises its accounting floor to this release.
--
-- DELIBERATELY NARROW. The rest of what check-release-seed-coverage reports -- the Build Journal
-- Entry Batches / Run ERP Sync actions, the two posting jobs (declared Active, so seeding them
-- would switch on ERP posting on every host) and the ML bench output -- is left out on purpose and
-- needs its own decision.
--
-- TRANSFORM: `EXEC [__mj_BizAppsAccounting]` -> `EXEC [${flyway:defaultSchema}]` (2). Each create is
-- guarded on ID OR Name (UQ_GLAccountRole_Name), so a host that already has a role from
-- `mj sync push` under its own ID skips it. Idempotent.
-- =============================================================================================
-- SQL Logging Session
-- Session ID: d1b042bf-e16b-40ae-a475-05db41a1695b
-- Started: 2026-09-29T00:01:38.343Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_2df9158a9cd1 UNIQUEIDENTIFIER,
@Name_2df9158a9cd1 NVARCHAR(100),
@Description_2df9158a9cd1 NVARCHAR(MAX),
@Status_2df9158a9cd1 NVARCHAR(10),
@Sequence_2df9158a9cd1 INT,
@Cardinality_2df9158a9cd1 NVARCHAR(10)
SET
  @ID_2df9158a9cd1 = '3EFC77F3-2468-463F-9197-D0A8A6762A36'
SET
  @Name_2df9158a9cd1 = N'Unbilled Receivable'
SET
  @Description_2df9158a9cd1 = N'Contract-asset account for revenue earned ahead of billing (orders D92). It is debited when revenue is recognised beyond what an order line has been billed, and credited when a later instalment invoice bills that amount down — so it holds service already delivered that the contract does not yet allow us to bill, while Accounts Receivable means billed and unpaid. Maps to 11300 Unbilled Revenue (Contract Asset), one company-level link per company; with no link the contract asset is folded into Deferred Revenue and a warning is logged, so the position is still correct and balanced but cannot be told apart from unearned billing.'
SET
  @Status_2df9158a9cd1 = N'Active'
SET
  @Sequence_2df9158a9cd1 = 100
SET
  @Cardinality_2df9158a9cd1 = N'One' 
IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[GLAccountRole]
               WHERE [ID] = @ID_2df9158a9cd1
                  OR ([Name] = @Name_2df9158a9cd1))
EXEC [${flyway:defaultSchema}].spCreateGLAccountRole @ID = @ID_2df9158a9cd1,
  @Name = @Name_2df9158a9cd1,
  @Description = @Description_2df9158a9cd1,
  @Status = @Status_2df9158a9cd1,
  @Sequence = @Sequence_2df9158a9cd1,
  @Cardinality = @Cardinality_2df9158a9cd1;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_76c05f75d456 UNIQUEIDENTIFIER,
@Name_76c05f75d456 NVARCHAR(100),
@Description_76c05f75d456 NVARCHAR(MAX),
@Status_76c05f75d456 NVARCHAR(10),
@Sequence_76c05f75d456 INT,
@Cardinality_76c05f75d456 NVARCHAR(10)
SET
  @ID_76c05f75d456 = '30F23B36-3BEB-4687-BF49-A5607A9B268A'
SET
  @Name_76c05f75d456 = N'Customer Deposits'
SET
  @Description_76c05f75d456 = N'Liability account for cash received against an order instalment that has not been invoiced yet (orders #234). A payment credits it for the part no invoice covers, a refund of that cash debits it, and issuing the instalment clears it against Accounts Receivable, so the balance is only ever money held ahead of billing. Resolved like every other role: product, product category, product type, then company. Finance may link it to a dedicated Customer Deposits account or to the Deferred Revenue account; the entries are the same either way. With no link, orders refuses a payment that needs this leg and names the role and the company.'
SET
  @Status_76c05f75d456 = N'Active'
SET
  @Sequence_76c05f75d456 = 110
SET
  @Cardinality_76c05f75d456 = N'One' 
IF NOT EXISTS (SELECT 1 FROM [${flyway:defaultSchema}].[GLAccountRole]
               WHERE [ID] = @ID_76c05f75d456
                  OR ([Name] = @Name_76c05f75d456))
EXEC [${flyway:defaultSchema}].spCreateGLAccountRole @ID = @ID_76c05f75d456,
  @Name = @Name_76c05f75d456,
  @Description = @Description_76c05f75d456,
  @Status = @Status_76c05f75d456,
  @Sequence = @Sequence_76c05f75d456,
  @Cardinality = @Cardinality_76c05f75d456;

GO


-- End of SQL Logging Session
-- Session ID: d1b042bf-e16b-40ae-a475-05db41a1695b
-- Completed: 2026-09-29T00:01:41.025Z
-- Duration: 2682ms
-- Total Statements: 2
