-- SQL Logging Session
-- Session ID: 847356c9-daf6-4304-ba5c-2fe1506f476b
-- Started: 2026-07-01T18:51:16.110Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Schema Info (core SP call only)
DECLARE @SchemaName_7faa14a0 NVARCHAR(50),
@EntityIDMin_7faa14a0 INT,
@EntityIDMax_7faa14a0 INT,
@Comments_7faa14a0 NVARCHAR(MAX),
@Description_7faa14a0 NVARCHAR(MAX),
@EntityNamePrefix_7faa14a0 NVARCHAR(25),
@EntityNameSuffix_7faa14a0 NVARCHAR(25),
@ID_7faa14a0 UNIQUEIDENTIFIER
SET
  @SchemaName_7faa14a0 = N'__mj_BizAppsAccounting'
SET
  @EntityIDMin_7faa14a0 = 1
SET
  @EntityIDMax_7faa14a0 = 1000000
SET
  @Description_7faa14a0 = N'MemberJunction BizApps Accounting — AR subledger and journal-entry primitives'
SET
  @EntityNamePrefix_7faa14a0 = N'MJ_BizApps_Accounting: '
SET
  @ID_7faa14a0 = '7F2F85AF-0DCF-4DF3-939A-38EA459AC820' EXEC [__mj].spUpdateSchemaInfo @SchemaName = @SchemaName_7faa14a0,
  @EntityIDMin = @EntityIDMin_7faa14a0,
  @EntityIDMax = @EntityIDMax_7faa14a0,
  @Comments = @Comments_7faa14a0,
  @Comments_Clear = 1,
  @Description = @Description_7faa14a0,
  @EntityNamePrefix = @EntityNamePrefix_7faa14a0,
  @EntityNameSuffix = @EntityNameSuffix_7faa14a0,
  @EntityNameSuffix_Clear = 1,
  @ID = @ID_7faa14a0;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_c4beaece UNIQUEIDENTIFIER,
@Code_c4beaece CHAR(3),
@Name_c4beaece NVARCHAR(80),
@Symbol_c4beaece NVARCHAR(10),
@DecimalPlaces_c4beaece TINYINT,
@IsActive_c4beaece BIT
SET
  @ID_c4beaece = '8AE23703-5276-40D1-9FB7-E11D56259933'
SET
  @Code_c4beaece = 'USD'
SET
  @Name_c4beaece = N'US Dollar'
SET
  @Symbol_c4beaece = N'$'
SET
  @DecimalPlaces_c4beaece = 2
SET
  @IsActive_c4beaece = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_c4beaece,
  @Code = @Code_c4beaece,
  @Name = @Name_c4beaece,
  @Symbol = @Symbol_c4beaece,
  @DecimalPlaces = @DecimalPlaces_c4beaece,
  @IsActive = @IsActive_c4beaece;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_0018f0ec UNIQUEIDENTIFIER,
@Code_0018f0ec CHAR(3),
@Name_0018f0ec NVARCHAR(80),
@Symbol_0018f0ec NVARCHAR(10),
@DecimalPlaces_0018f0ec TINYINT,
@IsActive_0018f0ec BIT
SET
  @ID_0018f0ec = '49696991-D874-4B4C-A2C5-9892FF8F5662'
SET
  @Code_0018f0ec = 'EUR'
SET
  @Name_0018f0ec = N'Euro'
SET
  @Symbol_0018f0ec = N'€'
SET
  @DecimalPlaces_0018f0ec = 2
SET
  @IsActive_0018f0ec = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_0018f0ec,
  @Code = @Code_0018f0ec,
  @Name = @Name_0018f0ec,
  @Symbol = @Symbol_0018f0ec,
  @DecimalPlaces = @DecimalPlaces_0018f0ec,
  @IsActive = @IsActive_0018f0ec;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_cba11033 UNIQUEIDENTIFIER,
@Code_cba11033 CHAR(3),
@Name_cba11033 NVARCHAR(80),
@Symbol_cba11033 NVARCHAR(10),
@DecimalPlaces_cba11033 TINYINT,
@IsActive_cba11033 BIT
SET
  @ID_cba11033 = 'E22DD818-5DA5-46A5-9FD4-AEAEDE4266DF'
SET
  @Code_cba11033 = 'GBP'
SET
  @Name_cba11033 = N'British Pound'
SET
  @Symbol_cba11033 = N'£'
SET
  @DecimalPlaces_cba11033 = 2
SET
  @IsActive_cba11033 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_cba11033,
  @Code = @Code_cba11033,
  @Name = @Name_cba11033,
  @Symbol = @Symbol_cba11033,
  @DecimalPlaces = @DecimalPlaces_cba11033,
  @IsActive = @IsActive_cba11033;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_f6fe3b6b UNIQUEIDENTIFIER,
@Code_f6fe3b6b CHAR(3),
@Name_f6fe3b6b NVARCHAR(80),
@Symbol_f6fe3b6b NVARCHAR(10),
@DecimalPlaces_f6fe3b6b TINYINT,
@IsActive_f6fe3b6b BIT
SET
  @ID_f6fe3b6b = 'D3EA8B9C-2F82-471A-BFDA-219F68DED825'
SET
  @Code_f6fe3b6b = 'JPY'
SET
  @Name_f6fe3b6b = N'Japanese Yen'
SET
  @Symbol_f6fe3b6b = N'¥'
SET
  @DecimalPlaces_f6fe3b6b = 0
SET
  @IsActive_f6fe3b6b = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_f6fe3b6b,
  @Code = @Code_f6fe3b6b,
  @Name = @Name_f6fe3b6b,
  @Symbol = @Symbol_f6fe3b6b,
  @DecimalPlaces = @DecimalPlaces_f6fe3b6b,
  @IsActive = @IsActive_f6fe3b6b;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_98c7d473 UNIQUEIDENTIFIER,
@Code_98c7d473 CHAR(3),
@Name_98c7d473 NVARCHAR(80),
@Symbol_98c7d473 NVARCHAR(10),
@DecimalPlaces_98c7d473 TINYINT,
@IsActive_98c7d473 BIT
SET
  @ID_98c7d473 = '2467644C-B3E0-4D62-9165-47DEA4AA86BA'
SET
  @Code_98c7d473 = 'CAD'
SET
  @Name_98c7d473 = N'Canadian Dollar'
SET
  @Symbol_98c7d473 = N'CA$'
SET
  @DecimalPlaces_98c7d473 = 2
SET
  @IsActive_98c7d473 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_98c7d473,
  @Code = @Code_98c7d473,
  @Name = @Name_98c7d473,
  @Symbol = @Symbol_98c7d473,
  @DecimalPlaces = @DecimalPlaces_98c7d473,
  @IsActive = @IsActive_98c7d473;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_3988bec8 UNIQUEIDENTIFIER,
@Code_3988bec8 CHAR(3),
@Name_3988bec8 NVARCHAR(80),
@Symbol_3988bec8 NVARCHAR(10),
@DecimalPlaces_3988bec8 TINYINT,
@IsActive_3988bec8 BIT
SET
  @ID_3988bec8 = 'BE959CC9-7DD6-4310-8D3F-FD1F5BC306E2'
SET
  @Code_3988bec8 = 'AUD'
SET
  @Name_3988bec8 = N'Australian Dollar'
SET
  @Symbol_3988bec8 = N'A$'
SET
  @DecimalPlaces_3988bec8 = 2
SET
  @IsActive_3988bec8 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_3988bec8,
  @Code = @Code_3988bec8,
  @Name = @Name_3988bec8,
  @Symbol = @Symbol_3988bec8,
  @DecimalPlaces = @DecimalPlaces_3988bec8,
  @IsActive = @IsActive_3988bec8;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_5845aa39 UNIQUEIDENTIFIER,
@Code_5845aa39 CHAR(3),
@Name_5845aa39 NVARCHAR(80),
@Symbol_5845aa39 NVARCHAR(10),
@DecimalPlaces_5845aa39 TINYINT,
@IsActive_5845aa39 BIT
SET
  @ID_5845aa39 = '9F35EFF4-8088-401C-A6F7-5EB67586F8B6'
SET
  @Code_5845aa39 = 'NZD'
SET
  @Name_5845aa39 = N'New Zealand Dollar'
SET
  @Symbol_5845aa39 = N'NZ$'
SET
  @DecimalPlaces_5845aa39 = 2
SET
  @IsActive_5845aa39 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_5845aa39,
  @Code = @Code_5845aa39,
  @Name = @Name_5845aa39,
  @Symbol = @Symbol_5845aa39,
  @DecimalPlaces = @DecimalPlaces_5845aa39,
  @IsActive = @IsActive_5845aa39;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_5793b254 UNIQUEIDENTIFIER,
@Code_5793b254 CHAR(3),
@Name_5793b254 NVARCHAR(80),
@Symbol_5793b254 NVARCHAR(10),
@DecimalPlaces_5793b254 TINYINT,
@IsActive_5793b254 BIT
SET
  @ID_5793b254 = 'FF8FAE1E-78DC-4816-B36F-88C821DFF25A'
SET
  @Code_5793b254 = 'CHF'
SET
  @Name_5793b254 = N'Swiss Franc'
SET
  @Symbol_5793b254 = N'CHF'
SET
  @DecimalPlaces_5793b254 = 2
SET
  @IsActive_5793b254 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_5793b254,
  @Code = @Code_5793b254,
  @Name = @Name_5793b254,
  @Symbol = @Symbol_5793b254,
  @DecimalPlaces = @DecimalPlaces_5793b254,
  @IsActive = @IsActive_5793b254;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_87391fb5 UNIQUEIDENTIFIER,
@Code_87391fb5 CHAR(3),
@Name_87391fb5 NVARCHAR(80),
@Symbol_87391fb5 NVARCHAR(10),
@DecimalPlaces_87391fb5 TINYINT,
@IsActive_87391fb5 BIT
SET
  @ID_87391fb5 = '0E384933-1DFF-493E-B3B2-A49BC4EA560C'
SET
  @Code_87391fb5 = 'CNY'
SET
  @Name_87391fb5 = N'Chinese Yuan'
SET
  @Symbol_87391fb5 = N'¥'
SET
  @DecimalPlaces_87391fb5 = 2
SET
  @IsActive_87391fb5 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_87391fb5,
  @Code = @Code_87391fb5,
  @Name = @Name_87391fb5,
  @Symbol = @Symbol_87391fb5,
  @DecimalPlaces = @DecimalPlaces_87391fb5,
  @IsActive = @IsActive_87391fb5;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_141057ac UNIQUEIDENTIFIER,
@Code_141057ac CHAR(3),
@Name_141057ac NVARCHAR(80),
@Symbol_141057ac NVARCHAR(10),
@DecimalPlaces_141057ac TINYINT,
@IsActive_141057ac BIT
SET
  @ID_141057ac = '3B08D5AA-911B-4CEF-B482-795B185BA766'
SET
  @Code_141057ac = 'HKD'
SET
  @Name_141057ac = N'Hong Kong Dollar'
SET
  @Symbol_141057ac = N'HK$'
SET
  @DecimalPlaces_141057ac = 2
SET
  @IsActive_141057ac = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_141057ac,
  @Code = @Code_141057ac,
  @Name = @Name_141057ac,
  @Symbol = @Symbol_141057ac,
  @DecimalPlaces = @DecimalPlaces_141057ac,
  @IsActive = @IsActive_141057ac;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_2ebb6cf5 UNIQUEIDENTIFIER,
@Code_2ebb6cf5 CHAR(3),
@Name_2ebb6cf5 NVARCHAR(80),
@Symbol_2ebb6cf5 NVARCHAR(10),
@DecimalPlaces_2ebb6cf5 TINYINT,
@IsActive_2ebb6cf5 BIT
SET
  @ID_2ebb6cf5 = '75D3AFEB-EA16-4AEE-BF5C-244175DF36D1'
SET
  @Code_2ebb6cf5 = 'SGD'
SET
  @Name_2ebb6cf5 = N'Singapore Dollar'
SET
  @Symbol_2ebb6cf5 = N'S$'
SET
  @DecimalPlaces_2ebb6cf5 = 2
SET
  @IsActive_2ebb6cf5 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_2ebb6cf5,
  @Code = @Code_2ebb6cf5,
  @Name = @Name_2ebb6cf5,
  @Symbol = @Symbol_2ebb6cf5,
  @DecimalPlaces = @DecimalPlaces_2ebb6cf5,
  @IsActive = @IsActive_2ebb6cf5;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_d3774d4f UNIQUEIDENTIFIER,
@Code_d3774d4f CHAR(3),
@Name_d3774d4f NVARCHAR(80),
@Symbol_d3774d4f NVARCHAR(10),
@DecimalPlaces_d3774d4f TINYINT,
@IsActive_d3774d4f BIT
SET
  @ID_d3774d4f = '94363986-743C-4D78-A22D-17E794426328'
SET
  @Code_d3774d4f = 'INR'
SET
  @Name_d3774d4f = N'Indian Rupee'
SET
  @Symbol_d3774d4f = N'₹'
SET
  @DecimalPlaces_d3774d4f = 2
SET
  @IsActive_d3774d4f = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_d3774d4f,
  @Code = @Code_d3774d4f,
  @Name = @Name_d3774d4f,
  @Symbol = @Symbol_d3774d4f,
  @DecimalPlaces = @DecimalPlaces_d3774d4f,
  @IsActive = @IsActive_d3774d4f;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_bc4406b9 UNIQUEIDENTIFIER,
@Code_bc4406b9 CHAR(3),
@Name_bc4406b9 NVARCHAR(80),
@Symbol_bc4406b9 NVARCHAR(10),
@DecimalPlaces_bc4406b9 TINYINT,
@IsActive_bc4406b9 BIT
SET
  @ID_bc4406b9 = '71CD0F28-ADE2-4D72-AD04-19C0E8B2EBA5'
SET
  @Code_bc4406b9 = 'MXN'
SET
  @Name_bc4406b9 = N'Mexican Peso'
SET
  @Symbol_bc4406b9 = N'MX$'
SET
  @DecimalPlaces_bc4406b9 = 2
SET
  @IsActive_bc4406b9 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_bc4406b9,
  @Code = @Code_bc4406b9,
  @Name = @Name_bc4406b9,
  @Symbol = @Symbol_bc4406b9,
  @DecimalPlaces = @DecimalPlaces_bc4406b9,
  @IsActive = @IsActive_bc4406b9;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_0492e41a UNIQUEIDENTIFIER,
@Code_0492e41a CHAR(3),
@Name_0492e41a NVARCHAR(80),
@Symbol_0492e41a NVARCHAR(10),
@DecimalPlaces_0492e41a TINYINT,
@IsActive_0492e41a BIT
SET
  @ID_0492e41a = '5EA73613-9AF7-41C5-95FC-CE3D44387C48'
SET
  @Code_0492e41a = 'BRL'
SET
  @Name_0492e41a = N'Brazilian Real'
SET
  @Symbol_0492e41a = N'R$'
SET
  @DecimalPlaces_0492e41a = 2
SET
  @IsActive_0492e41a = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_0492e41a,
  @Code = @Code_0492e41a,
  @Name = @Name_0492e41a,
  @Symbol = @Symbol_0492e41a,
  @DecimalPlaces = @DecimalPlaces_0492e41a,
  @IsActive = @IsActive_0492e41a;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_94654942 UNIQUEIDENTIFIER,
@Code_94654942 CHAR(3),
@Name_94654942 NVARCHAR(80),
@Symbol_94654942 NVARCHAR(10),
@DecimalPlaces_94654942 TINYINT,
@IsActive_94654942 BIT
SET
  @ID_94654942 = '955EF238-3A01-4E81-846E-1E651DDFB7D8'
SET
  @Code_94654942 = 'ZAR'
SET
  @Name_94654942 = N'South African Rand'
SET
  @Symbol_94654942 = N'R'
SET
  @DecimalPlaces_94654942 = 2
SET
  @IsActive_94654942 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_94654942,
  @Code = @Code_94654942,
  @Name = @Name_94654942,
  @Symbol = @Symbol_94654942,
  @DecimalPlaces = @DecimalPlaces_94654942,
  @IsActive = @IsActive_94654942;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_7d5be93b UNIQUEIDENTIFIER,
@Code_7d5be93b CHAR(3),
@Name_7d5be93b NVARCHAR(80),
@Symbol_7d5be93b NVARCHAR(10),
@DecimalPlaces_7d5be93b TINYINT,
@IsActive_7d5be93b BIT
SET
  @ID_7d5be93b = '99AE85FD-5975-48FD-A15C-3F13BF7398C0'
SET
  @Code_7d5be93b = 'SEK'
SET
  @Name_7d5be93b = N'Swedish Krona'
SET
  @Symbol_7d5be93b = N'kr'
SET
  @DecimalPlaces_7d5be93b = 2
SET
  @IsActive_7d5be93b = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_7d5be93b,
  @Code = @Code_7d5be93b,
  @Name = @Name_7d5be93b,
  @Symbol = @Symbol_7d5be93b,
  @DecimalPlaces = @DecimalPlaces_7d5be93b,
  @IsActive = @IsActive_7d5be93b;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_4ad7d0ff UNIQUEIDENTIFIER,
@Code_4ad7d0ff CHAR(3),
@Name_4ad7d0ff NVARCHAR(80),
@Symbol_4ad7d0ff NVARCHAR(10),
@DecimalPlaces_4ad7d0ff TINYINT,
@IsActive_4ad7d0ff BIT
SET
  @ID_4ad7d0ff = '881480F2-10C7-4113-B245-9A5B1E1097B0'
SET
  @Code_4ad7d0ff = 'NOK'
SET
  @Name_4ad7d0ff = N'Norwegian Krone'
SET
  @Symbol_4ad7d0ff = N'kr'
SET
  @DecimalPlaces_4ad7d0ff = 2
SET
  @IsActive_4ad7d0ff = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_4ad7d0ff,
  @Code = @Code_4ad7d0ff,
  @Name = @Name_4ad7d0ff,
  @Symbol = @Symbol_4ad7d0ff,
  @DecimalPlaces = @DecimalPlaces_4ad7d0ff,
  @IsActive = @IsActive_4ad7d0ff;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_fc2f24f2 UNIQUEIDENTIFIER,
@Code_fc2f24f2 CHAR(3),
@Name_fc2f24f2 NVARCHAR(80),
@Symbol_fc2f24f2 NVARCHAR(10),
@DecimalPlaces_fc2f24f2 TINYINT,
@IsActive_fc2f24f2 BIT
SET
  @ID_fc2f24f2 = '35171166-1C67-4133-860F-F2380EF9B928'
SET
  @Code_fc2f24f2 = 'DKK'
SET
  @Name_fc2f24f2 = N'Danish Krone'
SET
  @Symbol_fc2f24f2 = N'kr'
SET
  @DecimalPlaces_fc2f24f2 = 2
SET
  @IsActive_fc2f24f2 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_fc2f24f2,
  @Code = @Code_fc2f24f2,
  @Name = @Name_fc2f24f2,
  @Symbol = @Symbol_fc2f24f2,
  @DecimalPlaces = @DecimalPlaces_fc2f24f2,
  @IsActive = @IsActive_fc2f24f2;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_9cf2761b UNIQUEIDENTIFIER,
@Code_9cf2761b CHAR(3),
@Name_9cf2761b NVARCHAR(80),
@Symbol_9cf2761b NVARCHAR(10),
@DecimalPlaces_9cf2761b TINYINT,
@IsActive_9cf2761b BIT
SET
  @ID_9cf2761b = 'A7F18885-AF9A-4938-9633-0E5D5709174F'
SET
  @Code_9cf2761b = 'AED'
SET
  @Name_9cf2761b = N'UAE Dirham'
SET
  @Symbol_9cf2761b = N'د.إ'
SET
  @DecimalPlaces_9cf2761b = 2
SET
  @IsActive_9cf2761b = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_9cf2761b,
  @Code = @Code_9cf2761b,
  @Name = @Name_9cf2761b,
  @Symbol = @Symbol_9cf2761b,
  @DecimalPlaces = @DecimalPlaces_9cf2761b,
  @IsActive = @IsActive_9cf2761b;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_52f055ed UNIQUEIDENTIFIER,
@Code_52f055ed CHAR(3),
@Name_52f055ed NVARCHAR(80),
@Symbol_52f055ed NVARCHAR(10),
@DecimalPlaces_52f055ed TINYINT,
@IsActive_52f055ed BIT
SET
  @ID_52f055ed = '88021737-A995-4857-86D4-CB6FAEA77435'
SET
  @Code_52f055ed = 'KRW'
SET
  @Name_52f055ed = N'South Korean Won'
SET
  @Symbol_52f055ed = N'₩'
SET
  @DecimalPlaces_52f055ed = 0
SET
  @IsActive_52f055ed = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_52f055ed,
  @Code = @Code_52f055ed,
  @Name = @Name_52f055ed,
  @Symbol = @Symbol_52f055ed,
  @DecimalPlaces = @DecimalPlaces_52f055ed,
  @IsActive = @IsActive_52f055ed;

GO

-- Save MJ: Applications (core SP call only)
DECLARE @ID_dd28faca UNIQUEIDENTIFIER,
@Name_dd28faca NVARCHAR(100),
@Description_dd28faca NVARCHAR(MAX),
@Icon_dd28faca NVARCHAR(500),
@DefaultForNewUser_dd28faca BIT,
@SchemaAutoAddNewEntities_dd28faca NVARCHAR(MAX),
@Color_dd28faca NVARCHAR(20),
@DefaultNavItems_dd28faca NVARCHAR(MAX),
@ClassName_dd28faca NVARCHAR(255),
@DefaultSequence_dd28faca INT,
@Status_dd28faca NVARCHAR(20),
@NavigationStyle_dd28faca NVARCHAR(20),
@TopNavLocation_dd28faca NVARCHAR(30),
@HideNavBarIconWhenActive_dd28faca BIT,
@Path_dd28faca NVARCHAR(100),
@AutoUpdatePath_dd28faca BIT,
@AgentSettings_dd28faca NVARCHAR(MAX)
SET
  @ID_dd28faca = '08B5D905-6FB3-438B-94E5-2C5FF021B794'
SET
  @Name_dd28faca = N'Accounting'
SET
  @Description_dd28faca = N'AR subledger, journal entries, and JE batch dispatch to the ERP'
SET
  @Icon_dd28faca = N'fa-solid fa-book'
SET
  @DefaultForNewUser_dd28faca = 0
SET
  @Color_dd28faca = N'#0076b6'
SET
  @DefaultNavItems_dd28faca = N'[
  {
    "Label": "Batches",
    "Icon": "fa-solid fa-paper-plane",
    "ResourceType": "Custom",
    "DriverClass": "BatchDispatchResource",
    "isDefault": true
  },
  {
    "Label": "Trial Balance & AR",
    "Icon": "fa-solid fa-scale-balanced",
    "ResourceType": "Custom",
    "DriverClass": "TrialBalanceARResource",
    "isDefault": false
  },
  {
    "Label": "Revenue & Tax",
    "Icon": "fa-solid fa-receipt",
    "ResourceType": "Custom",
    "DriverClass": "RevenueTaxResource",
    "isDefault": false
  },
  {
    "Label": "Batch Status",
    "Icon": "fa-solid fa-list-check",
    "ResourceType": "Custom",
    "DriverClass": "BatchStatusResource",
    "isDefault": false
  },
  {
    "Label": "Intercompany Flow",
    "Icon": "fa-solid fa-arrows-turn-to-dots",
    "ResourceType": "Custom",
    "DriverClass": "IntercompanyFlowResource",
    "isDefault": false
  },
  {
    "Label": "GL Accounts",
    "Icon": "fa-solid fa-list-tree",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: GL Accounts"
    },
    "isDefault": false
  },
  {
    "Label": "Journal Entries",
    "Icon": "fa-solid fa-book-open",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Journal Entries"
    },
    "isDefault": false
  },
  {
    "Label": "Periods",
    "Icon": "fa-solid fa-calendar-days",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Accounting Periods"
    },
    "isDefault": false
  },
  {
    "Label": "Dimensions",
    "Icon": "fa-solid fa-tags",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Dimensions"
    },
    "isDefault": false
  }
]'
SET
  @DefaultSequence_dd28faca = 2010
SET
  @Status_dd28faca = N'Active'
SET
  @NavigationStyle_dd28faca = N'App Switcher'
SET
  @HideNavBarIconWhenActive_dd28faca = 0
SET
  @Path_dd28faca = N'accounting'
SET
  @AutoUpdatePath_dd28faca = 1
EXEC [__mj].spCreateApplication @ID = @ID_dd28faca,
  @Name = @Name_dd28faca,
  @Description = @Description_dd28faca,
  @Icon = @Icon_dd28faca,
  @DefaultForNewUser = @DefaultForNewUser_dd28faca,
  @SchemaAutoAddNewEntities = @SchemaAutoAddNewEntities_dd28faca,
  @SchemaAutoAddNewEntities_Clear = 1,
  @Color = @Color_dd28faca,
  @DefaultNavItems = @DefaultNavItems_dd28faca,
  @ClassName = @ClassName_dd28faca,
  @ClassName_Clear = 1,
  @DefaultSequence = @DefaultSequence_dd28faca,
  @Status = @Status_dd28faca,
  @NavigationStyle = @NavigationStyle_dd28faca,
  @TopNavLocation = @TopNavLocation_dd28faca,
  @TopNavLocation_Clear = 1,
  @HideNavBarIconWhenActive = @HideNavBarIconWhenActive_dd28faca,
  @Path = @Path_dd28faca,
  @AutoUpdatePath = @AutoUpdatePath_dd28faca,
  @AgentSettings = @AgentSettings_dd28faca,
  @AgentSettings_Clear = 1;

GO


-- End of SQL Logging Session
-- Session ID: 847356c9-daf6-4304-ba5c-2fe1506f476b
-- Completed: 2026-07-01T18:51:17.084Z
-- Duration: 974ms
-- Total Statements: 22
