-- SQL Logging Session
-- Session ID: b9ee8978-3db0-43e3-be10-42d83fd4b175
-- Started: 2026-07-02T02:04:27.486Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Schema Info (core SP call only)
DECLARE @SchemaName_f5f7b979 NVARCHAR(50),
@EntityIDMin_f5f7b979 INT,
@EntityIDMax_f5f7b979 INT,
@Comments_f5f7b979 NVARCHAR(MAX),
@Description_f5f7b979 NVARCHAR(MAX),
@EntityNamePrefix_f5f7b979 NVARCHAR(25),
@EntityNameSuffix_f5f7b979 NVARCHAR(25),
@CanonicalSchemaName_f5f7b979 NVARCHAR(50),
@ID_f5f7b979 UNIQUEIDENTIFIER
SET
  @SchemaName_f5f7b979 = N'__mj_BizAppsAccounting'
SET
  @EntityIDMin_f5f7b979 = 1
SET
  @EntityIDMax_f5f7b979 = 1000000
SET
  @Description_f5f7b979 = N'MemberJunction BizApps Accounting — AR subledger and journal-entry primitives'
SET
  @EntityNamePrefix_f5f7b979 = N'MJ_BizApps_Accounting: '
SET
  @CanonicalSchemaName_f5f7b979 = N'__mj_BizAppsAccounting'
SET
  @ID_f5f7b979 = '7F2F85AF-0DCF-4DF3-939A-38EA459AC820' EXEC [__mj].spUpdateSchemaInfo @SchemaName = @SchemaName_f5f7b979,
  @EntityIDMin = @EntityIDMin_f5f7b979,
  @EntityIDMax = @EntityIDMax_f5f7b979,
  @Comments = @Comments_f5f7b979,
  @Comments_Clear = 1,
  @Description = @Description_f5f7b979,
  @EntityNamePrefix = @EntityNamePrefix_f5f7b979,
  @EntityNameSuffix = @EntityNameSuffix_f5f7b979,
  @EntityNameSuffix_Clear = 1,
  @CanonicalSchemaName = @CanonicalSchemaName_f5f7b979,
  @ID = @ID_f5f7b979;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_c101ce1a UNIQUEIDENTIFIER,
@Code_c101ce1a CHAR(3),
@Name_c101ce1a NVARCHAR(80),
@Symbol_c101ce1a NVARCHAR(10),
@DecimalPlaces_c101ce1a TINYINT,
@IsActive_c101ce1a BIT
SET
  @ID_c101ce1a = '8AE23703-5276-40D1-9FB7-E11D56259933'
SET
  @Code_c101ce1a = 'USD'
SET
  @Name_c101ce1a = N'US Dollar'
SET
  @Symbol_c101ce1a = N'$'
SET
  @DecimalPlaces_c101ce1a = 2
SET
  @IsActive_c101ce1a = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_c101ce1a,
  @Code = @Code_c101ce1a,
  @Name = @Name_c101ce1a,
  @Symbol = @Symbol_c101ce1a,
  @DecimalPlaces = @DecimalPlaces_c101ce1a,
  @IsActive = @IsActive_c101ce1a;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_b40df5a8 UNIQUEIDENTIFIER,
@Code_b40df5a8 CHAR(3),
@Name_b40df5a8 NVARCHAR(80),
@Symbol_b40df5a8 NVARCHAR(10),
@DecimalPlaces_b40df5a8 TINYINT,
@IsActive_b40df5a8 BIT
SET
  @ID_b40df5a8 = '49696991-D874-4B4C-A2C5-9892FF8F5662'
SET
  @Code_b40df5a8 = 'EUR'
SET
  @Name_b40df5a8 = N'Euro'
SET
  @Symbol_b40df5a8 = N'€'
SET
  @DecimalPlaces_b40df5a8 = 2
SET
  @IsActive_b40df5a8 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_b40df5a8,
  @Code = @Code_b40df5a8,
  @Name = @Name_b40df5a8,
  @Symbol = @Symbol_b40df5a8,
  @DecimalPlaces = @DecimalPlaces_b40df5a8,
  @IsActive = @IsActive_b40df5a8;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_8203a30e UNIQUEIDENTIFIER,
@Code_8203a30e CHAR(3),
@Name_8203a30e NVARCHAR(80),
@Symbol_8203a30e NVARCHAR(10),
@DecimalPlaces_8203a30e TINYINT,
@IsActive_8203a30e BIT
SET
  @ID_8203a30e = 'E22DD818-5DA5-46A5-9FD4-AEAEDE4266DF'
SET
  @Code_8203a30e = 'GBP'
SET
  @Name_8203a30e = N'British Pound'
SET
  @Symbol_8203a30e = N'£'
SET
  @DecimalPlaces_8203a30e = 2
SET
  @IsActive_8203a30e = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_8203a30e,
  @Code = @Code_8203a30e,
  @Name = @Name_8203a30e,
  @Symbol = @Symbol_8203a30e,
  @DecimalPlaces = @DecimalPlaces_8203a30e,
  @IsActive = @IsActive_8203a30e;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_9573db00 UNIQUEIDENTIFIER,
@Code_9573db00 CHAR(3),
@Name_9573db00 NVARCHAR(80),
@Symbol_9573db00 NVARCHAR(10),
@DecimalPlaces_9573db00 TINYINT,
@IsActive_9573db00 BIT
SET
  @ID_9573db00 = 'D3EA8B9C-2F82-471A-BFDA-219F68DED825'
SET
  @Code_9573db00 = 'JPY'
SET
  @Name_9573db00 = N'Japanese Yen'
SET
  @Symbol_9573db00 = N'¥'
SET
  @DecimalPlaces_9573db00 = 0
SET
  @IsActive_9573db00 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_9573db00,
  @Code = @Code_9573db00,
  @Name = @Name_9573db00,
  @Symbol = @Symbol_9573db00,
  @DecimalPlaces = @DecimalPlaces_9573db00,
  @IsActive = @IsActive_9573db00;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_220e7dbe UNIQUEIDENTIFIER,
@Code_220e7dbe CHAR(3),
@Name_220e7dbe NVARCHAR(80),
@Symbol_220e7dbe NVARCHAR(10),
@DecimalPlaces_220e7dbe TINYINT,
@IsActive_220e7dbe BIT
SET
  @ID_220e7dbe = '2467644C-B3E0-4D62-9165-47DEA4AA86BA'
SET
  @Code_220e7dbe = 'CAD'
SET
  @Name_220e7dbe = N'Canadian Dollar'
SET
  @Symbol_220e7dbe = N'CA$'
SET
  @DecimalPlaces_220e7dbe = 2
SET
  @IsActive_220e7dbe = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_220e7dbe,
  @Code = @Code_220e7dbe,
  @Name = @Name_220e7dbe,
  @Symbol = @Symbol_220e7dbe,
  @DecimalPlaces = @DecimalPlaces_220e7dbe,
  @IsActive = @IsActive_220e7dbe;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_416ce59b UNIQUEIDENTIFIER,
@Code_416ce59b CHAR(3),
@Name_416ce59b NVARCHAR(80),
@Symbol_416ce59b NVARCHAR(10),
@DecimalPlaces_416ce59b TINYINT,
@IsActive_416ce59b BIT
SET
  @ID_416ce59b = 'BE959CC9-7DD6-4310-8D3F-FD1F5BC306E2'
SET
  @Code_416ce59b = 'AUD'
SET
  @Name_416ce59b = N'Australian Dollar'
SET
  @Symbol_416ce59b = N'A$'
SET
  @DecimalPlaces_416ce59b = 2
SET
  @IsActive_416ce59b = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_416ce59b,
  @Code = @Code_416ce59b,
  @Name = @Name_416ce59b,
  @Symbol = @Symbol_416ce59b,
  @DecimalPlaces = @DecimalPlaces_416ce59b,
  @IsActive = @IsActive_416ce59b;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_cf1cff39 UNIQUEIDENTIFIER,
@Code_cf1cff39 CHAR(3),
@Name_cf1cff39 NVARCHAR(80),
@Symbol_cf1cff39 NVARCHAR(10),
@DecimalPlaces_cf1cff39 TINYINT,
@IsActive_cf1cff39 BIT
SET
  @ID_cf1cff39 = '9F35EFF4-8088-401C-A6F7-5EB67586F8B6'
SET
  @Code_cf1cff39 = 'NZD'
SET
  @Name_cf1cff39 = N'New Zealand Dollar'
SET
  @Symbol_cf1cff39 = N'NZ$'
SET
  @DecimalPlaces_cf1cff39 = 2
SET
  @IsActive_cf1cff39 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_cf1cff39,
  @Code = @Code_cf1cff39,
  @Name = @Name_cf1cff39,
  @Symbol = @Symbol_cf1cff39,
  @DecimalPlaces = @DecimalPlaces_cf1cff39,
  @IsActive = @IsActive_cf1cff39;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_5c766de4 UNIQUEIDENTIFIER,
@Code_5c766de4 CHAR(3),
@Name_5c766de4 NVARCHAR(80),
@Symbol_5c766de4 NVARCHAR(10),
@DecimalPlaces_5c766de4 TINYINT,
@IsActive_5c766de4 BIT
SET
  @ID_5c766de4 = 'FF8FAE1E-78DC-4816-B36F-88C821DFF25A'
SET
  @Code_5c766de4 = 'CHF'
SET
  @Name_5c766de4 = N'Swiss Franc'
SET
  @Symbol_5c766de4 = N'CHF'
SET
  @DecimalPlaces_5c766de4 = 2
SET
  @IsActive_5c766de4 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_5c766de4,
  @Code = @Code_5c766de4,
  @Name = @Name_5c766de4,
  @Symbol = @Symbol_5c766de4,
  @DecimalPlaces = @DecimalPlaces_5c766de4,
  @IsActive = @IsActive_5c766de4;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_93dfb152 UNIQUEIDENTIFIER,
@Code_93dfb152 CHAR(3),
@Name_93dfb152 NVARCHAR(80),
@Symbol_93dfb152 NVARCHAR(10),
@DecimalPlaces_93dfb152 TINYINT,
@IsActive_93dfb152 BIT
SET
  @ID_93dfb152 = '0E384933-1DFF-493E-B3B2-A49BC4EA560C'
SET
  @Code_93dfb152 = 'CNY'
SET
  @Name_93dfb152 = N'Chinese Yuan'
SET
  @Symbol_93dfb152 = N'¥'
SET
  @DecimalPlaces_93dfb152 = 2
SET
  @IsActive_93dfb152 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_93dfb152,
  @Code = @Code_93dfb152,
  @Name = @Name_93dfb152,
  @Symbol = @Symbol_93dfb152,
  @DecimalPlaces = @DecimalPlaces_93dfb152,
  @IsActive = @IsActive_93dfb152;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_8e19918f UNIQUEIDENTIFIER,
@Code_8e19918f CHAR(3),
@Name_8e19918f NVARCHAR(80),
@Symbol_8e19918f NVARCHAR(10),
@DecimalPlaces_8e19918f TINYINT,
@IsActive_8e19918f BIT
SET
  @ID_8e19918f = '3B08D5AA-911B-4CEF-B482-795B185BA766'
SET
  @Code_8e19918f = 'HKD'
SET
  @Name_8e19918f = N'Hong Kong Dollar'
SET
  @Symbol_8e19918f = N'HK$'
SET
  @DecimalPlaces_8e19918f = 2
SET
  @IsActive_8e19918f = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_8e19918f,
  @Code = @Code_8e19918f,
  @Name = @Name_8e19918f,
  @Symbol = @Symbol_8e19918f,
  @DecimalPlaces = @DecimalPlaces_8e19918f,
  @IsActive = @IsActive_8e19918f;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_37fca455 UNIQUEIDENTIFIER,
@Code_37fca455 CHAR(3),
@Name_37fca455 NVARCHAR(80),
@Symbol_37fca455 NVARCHAR(10),
@DecimalPlaces_37fca455 TINYINT,
@IsActive_37fca455 BIT
SET
  @ID_37fca455 = '75D3AFEB-EA16-4AEE-BF5C-244175DF36D1'
SET
  @Code_37fca455 = 'SGD'
SET
  @Name_37fca455 = N'Singapore Dollar'
SET
  @Symbol_37fca455 = N'S$'
SET
  @DecimalPlaces_37fca455 = 2
SET
  @IsActive_37fca455 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_37fca455,
  @Code = @Code_37fca455,
  @Name = @Name_37fca455,
  @Symbol = @Symbol_37fca455,
  @DecimalPlaces = @DecimalPlaces_37fca455,
  @IsActive = @IsActive_37fca455;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_0b2b8794 UNIQUEIDENTIFIER,
@Code_0b2b8794 CHAR(3),
@Name_0b2b8794 NVARCHAR(80),
@Symbol_0b2b8794 NVARCHAR(10),
@DecimalPlaces_0b2b8794 TINYINT,
@IsActive_0b2b8794 BIT
SET
  @ID_0b2b8794 = '94363986-743C-4D78-A22D-17E794426328'
SET
  @Code_0b2b8794 = 'INR'
SET
  @Name_0b2b8794 = N'Indian Rupee'
SET
  @Symbol_0b2b8794 = N'₹'
SET
  @DecimalPlaces_0b2b8794 = 2
SET
  @IsActive_0b2b8794 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_0b2b8794,
  @Code = @Code_0b2b8794,
  @Name = @Name_0b2b8794,
  @Symbol = @Symbol_0b2b8794,
  @DecimalPlaces = @DecimalPlaces_0b2b8794,
  @IsActive = @IsActive_0b2b8794;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_a6f53bc5 UNIQUEIDENTIFIER,
@Code_a6f53bc5 CHAR(3),
@Name_a6f53bc5 NVARCHAR(80),
@Symbol_a6f53bc5 NVARCHAR(10),
@DecimalPlaces_a6f53bc5 TINYINT,
@IsActive_a6f53bc5 BIT
SET
  @ID_a6f53bc5 = '71CD0F28-ADE2-4D72-AD04-19C0E8B2EBA5'
SET
  @Code_a6f53bc5 = 'MXN'
SET
  @Name_a6f53bc5 = N'Mexican Peso'
SET
  @Symbol_a6f53bc5 = N'MX$'
SET
  @DecimalPlaces_a6f53bc5 = 2
SET
  @IsActive_a6f53bc5 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_a6f53bc5,
  @Code = @Code_a6f53bc5,
  @Name = @Name_a6f53bc5,
  @Symbol = @Symbol_a6f53bc5,
  @DecimalPlaces = @DecimalPlaces_a6f53bc5,
  @IsActive = @IsActive_a6f53bc5;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_c9bd8636 UNIQUEIDENTIFIER,
@Code_c9bd8636 CHAR(3),
@Name_c9bd8636 NVARCHAR(80),
@Symbol_c9bd8636 NVARCHAR(10),
@DecimalPlaces_c9bd8636 TINYINT,
@IsActive_c9bd8636 BIT
SET
  @ID_c9bd8636 = '5EA73613-9AF7-41C5-95FC-CE3D44387C48'
SET
  @Code_c9bd8636 = 'BRL'
SET
  @Name_c9bd8636 = N'Brazilian Real'
SET
  @Symbol_c9bd8636 = N'R$'
SET
  @DecimalPlaces_c9bd8636 = 2
SET
  @IsActive_c9bd8636 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_c9bd8636,
  @Code = @Code_c9bd8636,
  @Name = @Name_c9bd8636,
  @Symbol = @Symbol_c9bd8636,
  @DecimalPlaces = @DecimalPlaces_c9bd8636,
  @IsActive = @IsActive_c9bd8636;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_eaacae08 UNIQUEIDENTIFIER,
@Code_eaacae08 CHAR(3),
@Name_eaacae08 NVARCHAR(80),
@Symbol_eaacae08 NVARCHAR(10),
@DecimalPlaces_eaacae08 TINYINT,
@IsActive_eaacae08 BIT
SET
  @ID_eaacae08 = '955EF238-3A01-4E81-846E-1E651DDFB7D8'
SET
  @Code_eaacae08 = 'ZAR'
SET
  @Name_eaacae08 = N'South African Rand'
SET
  @Symbol_eaacae08 = N'R'
SET
  @DecimalPlaces_eaacae08 = 2
SET
  @IsActive_eaacae08 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_eaacae08,
  @Code = @Code_eaacae08,
  @Name = @Name_eaacae08,
  @Symbol = @Symbol_eaacae08,
  @DecimalPlaces = @DecimalPlaces_eaacae08,
  @IsActive = @IsActive_eaacae08;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_68bd3311 UNIQUEIDENTIFIER,
@Code_68bd3311 CHAR(3),
@Name_68bd3311 NVARCHAR(80),
@Symbol_68bd3311 NVARCHAR(10),
@DecimalPlaces_68bd3311 TINYINT,
@IsActive_68bd3311 BIT
SET
  @ID_68bd3311 = '99AE85FD-5975-48FD-A15C-3F13BF7398C0'
SET
  @Code_68bd3311 = 'SEK'
SET
  @Name_68bd3311 = N'Swedish Krona'
SET
  @Symbol_68bd3311 = N'kr'
SET
  @DecimalPlaces_68bd3311 = 2
SET
  @IsActive_68bd3311 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_68bd3311,
  @Code = @Code_68bd3311,
  @Name = @Name_68bd3311,
  @Symbol = @Symbol_68bd3311,
  @DecimalPlaces = @DecimalPlaces_68bd3311,
  @IsActive = @IsActive_68bd3311;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_fe036a05 UNIQUEIDENTIFIER,
@Code_fe036a05 CHAR(3),
@Name_fe036a05 NVARCHAR(80),
@Symbol_fe036a05 NVARCHAR(10),
@DecimalPlaces_fe036a05 TINYINT,
@IsActive_fe036a05 BIT
SET
  @ID_fe036a05 = '881480F2-10C7-4113-B245-9A5B1E1097B0'
SET
  @Code_fe036a05 = 'NOK'
SET
  @Name_fe036a05 = N'Norwegian Krone'
SET
  @Symbol_fe036a05 = N'kr'
SET
  @DecimalPlaces_fe036a05 = 2
SET
  @IsActive_fe036a05 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_fe036a05,
  @Code = @Code_fe036a05,
  @Name = @Name_fe036a05,
  @Symbol = @Symbol_fe036a05,
  @DecimalPlaces = @DecimalPlaces_fe036a05,
  @IsActive = @IsActive_fe036a05;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_b18d5cb0 UNIQUEIDENTIFIER,
@Code_b18d5cb0 CHAR(3),
@Name_b18d5cb0 NVARCHAR(80),
@Symbol_b18d5cb0 NVARCHAR(10),
@DecimalPlaces_b18d5cb0 TINYINT,
@IsActive_b18d5cb0 BIT
SET
  @ID_b18d5cb0 = '35171166-1C67-4133-860F-F2380EF9B928'
SET
  @Code_b18d5cb0 = 'DKK'
SET
  @Name_b18d5cb0 = N'Danish Krone'
SET
  @Symbol_b18d5cb0 = N'kr'
SET
  @DecimalPlaces_b18d5cb0 = 2
SET
  @IsActive_b18d5cb0 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_b18d5cb0,
  @Code = @Code_b18d5cb0,
  @Name = @Name_b18d5cb0,
  @Symbol = @Symbol_b18d5cb0,
  @DecimalPlaces = @DecimalPlaces_b18d5cb0,
  @IsActive = @IsActive_b18d5cb0;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_a54556d0 UNIQUEIDENTIFIER,
@Code_a54556d0 CHAR(3),
@Name_a54556d0 NVARCHAR(80),
@Symbol_a54556d0 NVARCHAR(10),
@DecimalPlaces_a54556d0 TINYINT,
@IsActive_a54556d0 BIT
SET
  @ID_a54556d0 = 'A7F18885-AF9A-4938-9633-0E5D5709174F'
SET
  @Code_a54556d0 = 'AED'
SET
  @Name_a54556d0 = N'UAE Dirham'
SET
  @Symbol_a54556d0 = N'د.إ'
SET
  @DecimalPlaces_a54556d0 = 2
SET
  @IsActive_a54556d0 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_a54556d0,
  @Code = @Code_a54556d0,
  @Name = @Name_a54556d0,
  @Symbol = @Symbol_a54556d0,
  @DecimalPlaces = @DecimalPlaces_a54556d0,
  @IsActive = @IsActive_a54556d0;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_d8daea88 UNIQUEIDENTIFIER,
@Code_d8daea88 CHAR(3),
@Name_d8daea88 NVARCHAR(80),
@Symbol_d8daea88 NVARCHAR(10),
@DecimalPlaces_d8daea88 TINYINT,
@IsActive_d8daea88 BIT
SET
  @ID_d8daea88 = '88021737-A995-4857-86D4-CB6FAEA77435'
SET
  @Code_d8daea88 = 'KRW'
SET
  @Name_d8daea88 = N'South Korean Won'
SET
  @Symbol_d8daea88 = N'₩'
SET
  @DecimalPlaces_d8daea88 = 0
SET
  @IsActive_d8daea88 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_d8daea88,
  @Code = @Code_d8daea88,
  @Name = @Name_d8daea88,
  @Symbol = @Symbol_d8daea88,
  @DecimalPlaces = @DecimalPlaces_d8daea88,
  @IsActive = @IsActive_d8daea88;

GO

-- Save MJ: Applications (core SP call only)
DECLARE @ID_df225e56 UNIQUEIDENTIFIER,
@Name_df225e56 NVARCHAR(100),
@Description_df225e56 NVARCHAR(MAX),
@Icon_df225e56 NVARCHAR(500),
@DefaultForNewUser_df225e56 BIT,
@SchemaAutoAddNewEntities_df225e56 NVARCHAR(MAX),
@Color_df225e56 NVARCHAR(20),
@DefaultNavItems_df225e56 NVARCHAR(MAX),
@ClassName_df225e56 NVARCHAR(255),
@DefaultSequence_df225e56 INT,
@Status_df225e56 NVARCHAR(20),
@NavigationStyle_df225e56 NVARCHAR(20),
@TopNavLocation_df225e56 NVARCHAR(30),
@HideNavBarIconWhenActive_df225e56 BIT,
@Path_df225e56 NVARCHAR(100),
@AutoUpdatePath_df225e56 BIT,
@AgentSettings_df225e56 NVARCHAR(MAX)
SET
  @ID_df225e56 = '08B5D905-6FB3-438B-94E5-2C5FF021B794'
SET
  @Name_df225e56 = N'Accounting'
SET
  @Description_df225e56 = N'AR subledger, journal entries, and JE batch dispatch to the ERP'
SET
  @Icon_df225e56 = N'fa-solid fa-book'
SET
  @DefaultForNewUser_df225e56 = 0
SET
  @Color_df225e56 = N'#0076b6'
SET
  @DefaultNavItems_df225e56 = N'[
  {
    "Label": "Batches",
    "Icon": "fa-solid fa-paper-plane",
    "ResourceType": "Custom",
    "DriverClass": "BatchDispatchResource",
    "isDefault": true
  },
  {
    "Label": "Trial Balance & AR",
    "Icon": "fa-solid fa-scale-balanced",
    "ResourceType": "Custom",
    "DriverClass": "TrialBalanceARResource",
    "isDefault": false
  },
  {
    "Label": "Revenue & Tax",
    "Icon": "fa-solid fa-receipt",
    "ResourceType": "Custom",
    "DriverClass": "RevenueTaxResource",
    "isDefault": false
  },
  {
    "Label": "Batch Status",
    "Icon": "fa-solid fa-list-check",
    "ResourceType": "Custom",
    "DriverClass": "BatchStatusResource",
    "isDefault": false
  },
  {
    "Label": "Intercompany Flow",
    "Icon": "fa-solid fa-arrows-turn-to-dots",
    "ResourceType": "Custom",
    "DriverClass": "IntercompanyFlowResource",
    "isDefault": false
  },
  {
    "Label": "GL Accounts",
    "Icon": "fa-solid fa-list-tree",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: GL Accounts"
    },
    "isDefault": false
  },
  {
    "Label": "Journal Entries",
    "Icon": "fa-solid fa-book-open",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Journal Entries"
    },
    "isDefault": false
  },
  {
    "Label": "Periods",
    "Icon": "fa-solid fa-calendar-days",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Accounting Periods"
    },
    "isDefault": false
  },
  {
    "Label": "Dimensions",
    "Icon": "fa-solid fa-tags",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Dimensions"
    },
    "isDefault": false
  }
]'
SET
  @DefaultSequence_df225e56 = 2010
SET
  @Status_df225e56 = N'Active'
SET
  @NavigationStyle_df225e56 = N'App Switcher'
SET
  @HideNavBarIconWhenActive_df225e56 = 0
SET
  @Path_df225e56 = N'accounting'
SET
  @AutoUpdatePath_df225e56 = 1
EXEC [__mj].spCreateApplication @ID = @ID_df225e56,
  @Name = @Name_df225e56,
  @Description = @Description_df225e56,
  @Icon = @Icon_df225e56,
  @DefaultForNewUser = @DefaultForNewUser_df225e56,
  @SchemaAutoAddNewEntities = @SchemaAutoAddNewEntities_df225e56,
  @SchemaAutoAddNewEntities_Clear = 1,
  @Color = @Color_df225e56,
  @DefaultNavItems = @DefaultNavItems_df225e56,
  @ClassName = @ClassName_df225e56,
  @ClassName_Clear = 1,
  @DefaultSequence = @DefaultSequence_df225e56,
  @Status = @Status_df225e56,
  @NavigationStyle = @NavigationStyle_df225e56,
  @TopNavLocation = @TopNavLocation_df225e56,
  @TopNavLocation_Clear = 1,
  @HideNavBarIconWhenActive = @HideNavBarIconWhenActive_df225e56,
  @Path = @Path_df225e56,
  @AutoUpdatePath = @AutoUpdatePath_df225e56,
  @AgentSettings = @AgentSettings_df225e56,
  @AgentSettings_Clear = 1;

GO


-- End of SQL Logging Session
-- Session ID: b9ee8978-3db0-43e3-be10-42d83fd4b175
-- Completed: 2026-07-02T02:04:28.558Z
-- Duration: 1072ms
-- Total Statements: 22
