-- =============================================================================
-- Metadata sync capture — regenerated 2026-07-06 against the reworked v1.0
-- baseline (supersedes the 2026-07-01 capture, which called CRUD sprocs that
-- no longer exist). Content: SchemaInfo description/prefix, the 20 seed
-- currencies, the 8 GL account roles (metadata/gl-account-roles), and the
-- application row. Captured verbatim from `mj sync push` SQL logging
-- (metadata/.mj-sync.json sqlLogging) during the ADR-009 setup loop.
-- Do NOT hand-edit: re-capture via a fresh `mj sync push` instead.
-- =============================================================================

-- SQL Logging Session
-- Session ID: 657474ba-83a8-4aeb-8e38-2614acc5b7a5
-- Started: 2026-07-06T08:27:57.366Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Schema Info (core SP call only)
DECLARE @SchemaName_98c49714 NVARCHAR(50),
@EntityIDMin_98c49714 INT,
@EntityIDMax_98c49714 INT,
@Comments_98c49714 NVARCHAR(MAX),
@Description_98c49714 NVARCHAR(MAX),
@EntityNamePrefix_98c49714 NVARCHAR(25),
@EntityNameSuffix_98c49714 NVARCHAR(25),
@CanonicalSchemaName_98c49714 NVARCHAR(50),
@ID_98c49714 UNIQUEIDENTIFIER
SET
  @SchemaName_98c49714 = N'__mj_BizAppsAccounting'
SET
  @EntityIDMin_98c49714 = 1
SET
  @EntityIDMax_98c49714 = 1000000
SET
  @Description_98c49714 = N'MemberJunction BizApps Accounting — AR subledger and journal-entry primitives'
SET
  @EntityNamePrefix_98c49714 = N'MJ_BizApps_Accounting: '
SET
  @CanonicalSchemaName_98c49714 = N'__mj_BizAppsAccounting'
SET
  @ID_98c49714 = '7F2F85AF-0DCF-4DF3-939A-38EA459AC820' EXEC [__mj].spUpdateSchemaInfo @SchemaName = @SchemaName_98c49714,
  @EntityIDMin = @EntityIDMin_98c49714,
  @EntityIDMax = @EntityIDMax_98c49714,
  @Comments = @Comments_98c49714,
  @Comments_Clear = 1,
  @Description = @Description_98c49714,
  @EntityNamePrefix = @EntityNamePrefix_98c49714,
  @EntityNameSuffix = @EntityNameSuffix_98c49714,
  @EntityNameSuffix_Clear = 1,
  @CanonicalSchemaName = @CanonicalSchemaName_98c49714,
  @ID = @ID_98c49714;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_5b400c8c UNIQUEIDENTIFIER,
@Code_5b400c8c CHAR(3),
@Name_5b400c8c NVARCHAR(80),
@Symbol_5b400c8c NVARCHAR(10),
@DecimalPlaces_5b400c8c TINYINT,
@IsActive_5b400c8c BIT
SET
  @ID_5b400c8c = '8AE23703-5276-40D1-9FB7-E11D56259933'
SET
  @Code_5b400c8c = 'USD'
SET
  @Name_5b400c8c = N'US Dollar'
SET
  @Symbol_5b400c8c = N'$'
SET
  @DecimalPlaces_5b400c8c = 2
SET
  @IsActive_5b400c8c = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_5b400c8c,
  @Code = @Code_5b400c8c,
  @Name = @Name_5b400c8c,
  @Symbol = @Symbol_5b400c8c,
  @DecimalPlaces = @DecimalPlaces_5b400c8c,
  @IsActive = @IsActive_5b400c8c;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_6852cac2 UNIQUEIDENTIFIER,
@Code_6852cac2 CHAR(3),
@Name_6852cac2 NVARCHAR(80),
@Symbol_6852cac2 NVARCHAR(10),
@DecimalPlaces_6852cac2 TINYINT,
@IsActive_6852cac2 BIT
SET
  @ID_6852cac2 = '49696991-D874-4B4C-A2C5-9892FF8F5662'
SET
  @Code_6852cac2 = 'EUR'
SET
  @Name_6852cac2 = N'Euro'
SET
  @Symbol_6852cac2 = N'€'
SET
  @DecimalPlaces_6852cac2 = 2
SET
  @IsActive_6852cac2 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_6852cac2,
  @Code = @Code_6852cac2,
  @Name = @Name_6852cac2,
  @Symbol = @Symbol_6852cac2,
  @DecimalPlaces = @DecimalPlaces_6852cac2,
  @IsActive = @IsActive_6852cac2;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_47b70ff9 UNIQUEIDENTIFIER,
@Code_47b70ff9 CHAR(3),
@Name_47b70ff9 NVARCHAR(80),
@Symbol_47b70ff9 NVARCHAR(10),
@DecimalPlaces_47b70ff9 TINYINT,
@IsActive_47b70ff9 BIT
SET
  @ID_47b70ff9 = 'E22DD818-5DA5-46A5-9FD4-AEAEDE4266DF'
SET
  @Code_47b70ff9 = 'GBP'
SET
  @Name_47b70ff9 = N'British Pound'
SET
  @Symbol_47b70ff9 = N'£'
SET
  @DecimalPlaces_47b70ff9 = 2
SET
  @IsActive_47b70ff9 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_47b70ff9,
  @Code = @Code_47b70ff9,
  @Name = @Name_47b70ff9,
  @Symbol = @Symbol_47b70ff9,
  @DecimalPlaces = @DecimalPlaces_47b70ff9,
  @IsActive = @IsActive_47b70ff9;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_647916b9 UNIQUEIDENTIFIER,
@Code_647916b9 CHAR(3),
@Name_647916b9 NVARCHAR(80),
@Symbol_647916b9 NVARCHAR(10),
@DecimalPlaces_647916b9 TINYINT,
@IsActive_647916b9 BIT
SET
  @ID_647916b9 = 'D3EA8B9C-2F82-471A-BFDA-219F68DED825'
SET
  @Code_647916b9 = 'JPY'
SET
  @Name_647916b9 = N'Japanese Yen'
SET
  @Symbol_647916b9 = N'¥'
SET
  @DecimalPlaces_647916b9 = 0
SET
  @IsActive_647916b9 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_647916b9,
  @Code = @Code_647916b9,
  @Name = @Name_647916b9,
  @Symbol = @Symbol_647916b9,
  @DecimalPlaces = @DecimalPlaces_647916b9,
  @IsActive = @IsActive_647916b9;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_dd0fc0e7 UNIQUEIDENTIFIER,
@Code_dd0fc0e7 CHAR(3),
@Name_dd0fc0e7 NVARCHAR(80),
@Symbol_dd0fc0e7 NVARCHAR(10),
@DecimalPlaces_dd0fc0e7 TINYINT,
@IsActive_dd0fc0e7 BIT
SET
  @ID_dd0fc0e7 = '2467644C-B3E0-4D62-9165-47DEA4AA86BA'
SET
  @Code_dd0fc0e7 = 'CAD'
SET
  @Name_dd0fc0e7 = N'Canadian Dollar'
SET
  @Symbol_dd0fc0e7 = N'CA$'
SET
  @DecimalPlaces_dd0fc0e7 = 2
SET
  @IsActive_dd0fc0e7 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_dd0fc0e7,
  @Code = @Code_dd0fc0e7,
  @Name = @Name_dd0fc0e7,
  @Symbol = @Symbol_dd0fc0e7,
  @DecimalPlaces = @DecimalPlaces_dd0fc0e7,
  @IsActive = @IsActive_dd0fc0e7;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_ace9443d UNIQUEIDENTIFIER,
@Code_ace9443d CHAR(3),
@Name_ace9443d NVARCHAR(80),
@Symbol_ace9443d NVARCHAR(10),
@DecimalPlaces_ace9443d TINYINT,
@IsActive_ace9443d BIT
SET
  @ID_ace9443d = 'BE959CC9-7DD6-4310-8D3F-FD1F5BC306E2'
SET
  @Code_ace9443d = 'AUD'
SET
  @Name_ace9443d = N'Australian Dollar'
SET
  @Symbol_ace9443d = N'A$'
SET
  @DecimalPlaces_ace9443d = 2
SET
  @IsActive_ace9443d = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_ace9443d,
  @Code = @Code_ace9443d,
  @Name = @Name_ace9443d,
  @Symbol = @Symbol_ace9443d,
  @DecimalPlaces = @DecimalPlaces_ace9443d,
  @IsActive = @IsActive_ace9443d;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_5622a675 UNIQUEIDENTIFIER,
@Code_5622a675 CHAR(3),
@Name_5622a675 NVARCHAR(80),
@Symbol_5622a675 NVARCHAR(10),
@DecimalPlaces_5622a675 TINYINT,
@IsActive_5622a675 BIT
SET
  @ID_5622a675 = '9F35EFF4-8088-401C-A6F7-5EB67586F8B6'
SET
  @Code_5622a675 = 'NZD'
SET
  @Name_5622a675 = N'New Zealand Dollar'
SET
  @Symbol_5622a675 = N'NZ$'
SET
  @DecimalPlaces_5622a675 = 2
SET
  @IsActive_5622a675 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_5622a675,
  @Code = @Code_5622a675,
  @Name = @Name_5622a675,
  @Symbol = @Symbol_5622a675,
  @DecimalPlaces = @DecimalPlaces_5622a675,
  @IsActive = @IsActive_5622a675;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_3bbbeb8d UNIQUEIDENTIFIER,
@Code_3bbbeb8d CHAR(3),
@Name_3bbbeb8d NVARCHAR(80),
@Symbol_3bbbeb8d NVARCHAR(10),
@DecimalPlaces_3bbbeb8d TINYINT,
@IsActive_3bbbeb8d BIT
SET
  @ID_3bbbeb8d = 'FF8FAE1E-78DC-4816-B36F-88C821DFF25A'
SET
  @Code_3bbbeb8d = 'CHF'
SET
  @Name_3bbbeb8d = N'Swiss Franc'
SET
  @Symbol_3bbbeb8d = N'CHF'
SET
  @DecimalPlaces_3bbbeb8d = 2
SET
  @IsActive_3bbbeb8d = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_3bbbeb8d,
  @Code = @Code_3bbbeb8d,
  @Name = @Name_3bbbeb8d,
  @Symbol = @Symbol_3bbbeb8d,
  @DecimalPlaces = @DecimalPlaces_3bbbeb8d,
  @IsActive = @IsActive_3bbbeb8d;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_7b7ccbea UNIQUEIDENTIFIER,
@Code_7b7ccbea CHAR(3),
@Name_7b7ccbea NVARCHAR(80),
@Symbol_7b7ccbea NVARCHAR(10),
@DecimalPlaces_7b7ccbea TINYINT,
@IsActive_7b7ccbea BIT
SET
  @ID_7b7ccbea = '0E384933-1DFF-493E-B3B2-A49BC4EA560C'
SET
  @Code_7b7ccbea = 'CNY'
SET
  @Name_7b7ccbea = N'Chinese Yuan'
SET
  @Symbol_7b7ccbea = N'¥'
SET
  @DecimalPlaces_7b7ccbea = 2
SET
  @IsActive_7b7ccbea = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_7b7ccbea,
  @Code = @Code_7b7ccbea,
  @Name = @Name_7b7ccbea,
  @Symbol = @Symbol_7b7ccbea,
  @DecimalPlaces = @DecimalPlaces_7b7ccbea,
  @IsActive = @IsActive_7b7ccbea;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_7e43dab4 UNIQUEIDENTIFIER,
@Code_7e43dab4 CHAR(3),
@Name_7e43dab4 NVARCHAR(80),
@Symbol_7e43dab4 NVARCHAR(10),
@DecimalPlaces_7e43dab4 TINYINT,
@IsActive_7e43dab4 BIT
SET
  @ID_7e43dab4 = '3B08D5AA-911B-4CEF-B482-795B185BA766'
SET
  @Code_7e43dab4 = 'HKD'
SET
  @Name_7e43dab4 = N'Hong Kong Dollar'
SET
  @Symbol_7e43dab4 = N'HK$'
SET
  @DecimalPlaces_7e43dab4 = 2
SET
  @IsActive_7e43dab4 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_7e43dab4,
  @Code = @Code_7e43dab4,
  @Name = @Name_7e43dab4,
  @Symbol = @Symbol_7e43dab4,
  @DecimalPlaces = @DecimalPlaces_7e43dab4,
  @IsActive = @IsActive_7e43dab4;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_97f0e967 UNIQUEIDENTIFIER,
@Code_97f0e967 CHAR(3),
@Name_97f0e967 NVARCHAR(80),
@Symbol_97f0e967 NVARCHAR(10),
@DecimalPlaces_97f0e967 TINYINT,
@IsActive_97f0e967 BIT
SET
  @ID_97f0e967 = '75D3AFEB-EA16-4AEE-BF5C-244175DF36D1'
SET
  @Code_97f0e967 = 'SGD'
SET
  @Name_97f0e967 = N'Singapore Dollar'
SET
  @Symbol_97f0e967 = N'S$'
SET
  @DecimalPlaces_97f0e967 = 2
SET
  @IsActive_97f0e967 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_97f0e967,
  @Code = @Code_97f0e967,
  @Name = @Name_97f0e967,
  @Symbol = @Symbol_97f0e967,
  @DecimalPlaces = @DecimalPlaces_97f0e967,
  @IsActive = @IsActive_97f0e967;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_53c767e3 UNIQUEIDENTIFIER,
@Code_53c767e3 CHAR(3),
@Name_53c767e3 NVARCHAR(80),
@Symbol_53c767e3 NVARCHAR(10),
@DecimalPlaces_53c767e3 TINYINT,
@IsActive_53c767e3 BIT
SET
  @ID_53c767e3 = '94363986-743C-4D78-A22D-17E794426328'
SET
  @Code_53c767e3 = 'INR'
SET
  @Name_53c767e3 = N'Indian Rupee'
SET
  @Symbol_53c767e3 = N'₹'
SET
  @DecimalPlaces_53c767e3 = 2
SET
  @IsActive_53c767e3 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_53c767e3,
  @Code = @Code_53c767e3,
  @Name = @Name_53c767e3,
  @Symbol = @Symbol_53c767e3,
  @DecimalPlaces = @DecimalPlaces_53c767e3,
  @IsActive = @IsActive_53c767e3;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_64c5a82b UNIQUEIDENTIFIER,
@Code_64c5a82b CHAR(3),
@Name_64c5a82b NVARCHAR(80),
@Symbol_64c5a82b NVARCHAR(10),
@DecimalPlaces_64c5a82b TINYINT,
@IsActive_64c5a82b BIT
SET
  @ID_64c5a82b = '71CD0F28-ADE2-4D72-AD04-19C0E8B2EBA5'
SET
  @Code_64c5a82b = 'MXN'
SET
  @Name_64c5a82b = N'Mexican Peso'
SET
  @Symbol_64c5a82b = N'MX$'
SET
  @DecimalPlaces_64c5a82b = 2
SET
  @IsActive_64c5a82b = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_64c5a82b,
  @Code = @Code_64c5a82b,
  @Name = @Name_64c5a82b,
  @Symbol = @Symbol_64c5a82b,
  @DecimalPlaces = @DecimalPlaces_64c5a82b,
  @IsActive = @IsActive_64c5a82b;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_9a2a3835 UNIQUEIDENTIFIER,
@Code_9a2a3835 CHAR(3),
@Name_9a2a3835 NVARCHAR(80),
@Symbol_9a2a3835 NVARCHAR(10),
@DecimalPlaces_9a2a3835 TINYINT,
@IsActive_9a2a3835 BIT
SET
  @ID_9a2a3835 = '5EA73613-9AF7-41C5-95FC-CE3D44387C48'
SET
  @Code_9a2a3835 = 'BRL'
SET
  @Name_9a2a3835 = N'Brazilian Real'
SET
  @Symbol_9a2a3835 = N'R$'
SET
  @DecimalPlaces_9a2a3835 = 2
SET
  @IsActive_9a2a3835 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_9a2a3835,
  @Code = @Code_9a2a3835,
  @Name = @Name_9a2a3835,
  @Symbol = @Symbol_9a2a3835,
  @DecimalPlaces = @DecimalPlaces_9a2a3835,
  @IsActive = @IsActive_9a2a3835;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_d149d1cc UNIQUEIDENTIFIER,
@Code_d149d1cc CHAR(3),
@Name_d149d1cc NVARCHAR(80),
@Symbol_d149d1cc NVARCHAR(10),
@DecimalPlaces_d149d1cc TINYINT,
@IsActive_d149d1cc BIT
SET
  @ID_d149d1cc = '955EF238-3A01-4E81-846E-1E651DDFB7D8'
SET
  @Code_d149d1cc = 'ZAR'
SET
  @Name_d149d1cc = N'South African Rand'
SET
  @Symbol_d149d1cc = N'R'
SET
  @DecimalPlaces_d149d1cc = 2
SET
  @IsActive_d149d1cc = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_d149d1cc,
  @Code = @Code_d149d1cc,
  @Name = @Name_d149d1cc,
  @Symbol = @Symbol_d149d1cc,
  @DecimalPlaces = @DecimalPlaces_d149d1cc,
  @IsActive = @IsActive_d149d1cc;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_ad6b5a0e UNIQUEIDENTIFIER,
@Code_ad6b5a0e CHAR(3),
@Name_ad6b5a0e NVARCHAR(80),
@Symbol_ad6b5a0e NVARCHAR(10),
@DecimalPlaces_ad6b5a0e TINYINT,
@IsActive_ad6b5a0e BIT
SET
  @ID_ad6b5a0e = '99AE85FD-5975-48FD-A15C-3F13BF7398C0'
SET
  @Code_ad6b5a0e = 'SEK'
SET
  @Name_ad6b5a0e = N'Swedish Krona'
SET
  @Symbol_ad6b5a0e = N'kr'
SET
  @DecimalPlaces_ad6b5a0e = 2
SET
  @IsActive_ad6b5a0e = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_ad6b5a0e,
  @Code = @Code_ad6b5a0e,
  @Name = @Name_ad6b5a0e,
  @Symbol = @Symbol_ad6b5a0e,
  @DecimalPlaces = @DecimalPlaces_ad6b5a0e,
  @IsActive = @IsActive_ad6b5a0e;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_9dc40d42 UNIQUEIDENTIFIER,
@Code_9dc40d42 CHAR(3),
@Name_9dc40d42 NVARCHAR(80),
@Symbol_9dc40d42 NVARCHAR(10),
@DecimalPlaces_9dc40d42 TINYINT,
@IsActive_9dc40d42 BIT
SET
  @ID_9dc40d42 = '881480F2-10C7-4113-B245-9A5B1E1097B0'
SET
  @Code_9dc40d42 = 'NOK'
SET
  @Name_9dc40d42 = N'Norwegian Krone'
SET
  @Symbol_9dc40d42 = N'kr'
SET
  @DecimalPlaces_9dc40d42 = 2
SET
  @IsActive_9dc40d42 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_9dc40d42,
  @Code = @Code_9dc40d42,
  @Name = @Name_9dc40d42,
  @Symbol = @Symbol_9dc40d42,
  @DecimalPlaces = @DecimalPlaces_9dc40d42,
  @IsActive = @IsActive_9dc40d42;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_fdbf9bae UNIQUEIDENTIFIER,
@Code_fdbf9bae CHAR(3),
@Name_fdbf9bae NVARCHAR(80),
@Symbol_fdbf9bae NVARCHAR(10),
@DecimalPlaces_fdbf9bae TINYINT,
@IsActive_fdbf9bae BIT
SET
  @ID_fdbf9bae = '35171166-1C67-4133-860F-F2380EF9B928'
SET
  @Code_fdbf9bae = 'DKK'
SET
  @Name_fdbf9bae = N'Danish Krone'
SET
  @Symbol_fdbf9bae = N'kr'
SET
  @DecimalPlaces_fdbf9bae = 2
SET
  @IsActive_fdbf9bae = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_fdbf9bae,
  @Code = @Code_fdbf9bae,
  @Name = @Name_fdbf9bae,
  @Symbol = @Symbol_fdbf9bae,
  @DecimalPlaces = @DecimalPlaces_fdbf9bae,
  @IsActive = @IsActive_fdbf9bae;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_d76ef7b6 UNIQUEIDENTIFIER,
@Code_d76ef7b6 CHAR(3),
@Name_d76ef7b6 NVARCHAR(80),
@Symbol_d76ef7b6 NVARCHAR(10),
@DecimalPlaces_d76ef7b6 TINYINT,
@IsActive_d76ef7b6 BIT
SET
  @ID_d76ef7b6 = 'A7F18885-AF9A-4938-9633-0E5D5709174F'
SET
  @Code_d76ef7b6 = 'AED'
SET
  @Name_d76ef7b6 = N'UAE Dirham'
SET
  @Symbol_d76ef7b6 = N'د.إ'
SET
  @DecimalPlaces_d76ef7b6 = 2
SET
  @IsActive_d76ef7b6 = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_d76ef7b6,
  @Code = @Code_d76ef7b6,
  @Name = @Name_d76ef7b6,
  @Symbol = @Symbol_d76ef7b6,
  @DecimalPlaces = @DecimalPlaces_d76ef7b6,
  @IsActive = @IsActive_d76ef7b6;

GO

-- Save MJ_BizApps_Accounting: Currencies (core SP call only)
DECLARE @ID_a80ee3ff UNIQUEIDENTIFIER,
@Code_a80ee3ff CHAR(3),
@Name_a80ee3ff NVARCHAR(80),
@Symbol_a80ee3ff NVARCHAR(10),
@DecimalPlaces_a80ee3ff TINYINT,
@IsActive_a80ee3ff BIT
SET
  @ID_a80ee3ff = '88021737-A995-4857-86D4-CB6FAEA77435'
SET
  @Code_a80ee3ff = 'KRW'
SET
  @Name_a80ee3ff = N'South Korean Won'
SET
  @Symbol_a80ee3ff = N'₩'
SET
  @DecimalPlaces_a80ee3ff = 0
SET
  @IsActive_a80ee3ff = 1
EXEC [__mj_BizAppsAccounting].spCreateCurrency @ID = @ID_a80ee3ff,
  @Code = @Code_a80ee3ff,
  @Name = @Name_a80ee3ff,
  @Symbol = @Symbol_a80ee3ff,
  @DecimalPlaces = @DecimalPlaces_a80ee3ff,
  @IsActive = @IsActive_a80ee3ff;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_d613bea1 UNIQUEIDENTIFIER,
@Name_d613bea1 NVARCHAR(100),
@Description_d613bea1 NVARCHAR(MAX),
@Status_d613bea1 NVARCHAR(10),
@Sequence_d613bea1 INT
SET
  @ID_d613bea1 = 'c00a0d5b-c267-4d38-a384-20be6fb813e4'
SET
  @Name_d613bea1 = N'Cash'
SET
  @Description_d613bea1 = N'Cash / bank account the money lands in (payment-time entries).'
SET
  @Status_d613bea1 = N'Active'
SET
  @Sequence_d613bea1 = 10
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_d613bea1,
  @Name = @Name_d613bea1,
  @Description = @Description_d613bea1,
  @Status = @Status_d613bea1,
  @Sequence = @Sequence_d613bea1;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_7fe52105 UNIQUEIDENTIFIER,
@Name_7fe52105 NVARCHAR(100),
@Description_7fe52105 NVARCHAR(MAX),
@Status_7fe52105 NVARCHAR(10),
@Sequence_7fe52105 INT
SET
  @ID_7fe52105 = '4567c215-9996-485e-82b9-fccc7ecd9b8e'
SET
  @Name_7fe52105 = N'Accounts Receivable'
SET
  @Description_7fe52105 = N'The AR control account debited when a sale is booked before payment.'
SET
  @Status_7fe52105 = N'Active'
SET
  @Sequence_7fe52105 = 20
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_7fe52105,
  @Name = @Name_7fe52105,
  @Description = @Description_7fe52105,
  @Status = @Status_7fe52105,
  @Sequence = @Sequence_7fe52105;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_ae559524 UNIQUEIDENTIFIER,
@Name_ae559524 NVARCHAR(100),
@Description_ae559524 NVARCHAR(MAX),
@Status_ae559524 NVARCHAR(10),
@Sequence_ae559524 INT
SET
  @ID_ae559524 = 'ec0dfa1e-4b57-4734-83b0-d20b72ac8968'
SET
  @Name_ae559524 = N'Inventory'
SET
  @Description_ae559524 = N'Inventory asset account (deferred domain - seeded per AM-2 for completeness).'
SET
  @Status_ae559524 = N'Active'
SET
  @Sequence_ae559524 = 30
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_ae559524,
  @Name = @Name_ae559524,
  @Description = @Description_ae559524,
  @Status = @Status_ae559524,
  @Sequence = @Sequence_ae559524;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_9d6f86b4 UNIQUEIDENTIFIER,
@Name_9d6f86b4 NVARCHAR(100),
@Description_9d6f86b4 NVARCHAR(MAX),
@Status_9d6f86b4 NVARCHAR(10),
@Sequence_9d6f86b4 INT
SET
  @ID_9d6f86b4 = '2466c088-3dfa-4dc7-92a6-34d40eaf1a91'
SET
  @Name_9d6f86b4 = N'Cost of Goods Sold'
SET
  @Description_9d6f86b4 = N'COGS expense account (deferred domain - seeded per AM-2 for completeness).'
SET
  @Status_9d6f86b4 = N'Active'
SET
  @Sequence_9d6f86b4 = 40
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_9d6f86b4,
  @Name = @Name_9d6f86b4,
  @Description = @Description_9d6f86b4,
  @Status = @Status_9d6f86b4,
  @Sequence = @Sequence_9d6f86b4;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_4b0ecdd1 UNIQUEIDENTIFIER,
@Name_4b0ecdd1 NVARCHAR(100),
@Description_4b0ecdd1 NVARCHAR(MAX),
@Status_4b0ecdd1 NVARCHAR(10),
@Sequence_4b0ecdd1 INT
SET
  @ID_4b0ecdd1 = 'f9dd0834-93c5-421c-a0a3-140c82f9e12a'
SET
  @Name_4b0ecdd1 = N'Sales'
SET
  @Description_4b0ecdd1 = N'Revenue account credited when a sale is recognized.'
SET
  @Status_4b0ecdd1 = N'Active'
SET
  @Sequence_4b0ecdd1 = 50
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_4b0ecdd1,
  @Name = @Name_4b0ecdd1,
  @Description = @Description_4b0ecdd1,
  @Status = @Status_4b0ecdd1,
  @Sequence = @Sequence_4b0ecdd1;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_924e7d98 UNIQUEIDENTIFIER,
@Name_924e7d98 NVARCHAR(100),
@Description_924e7d98 NVARCHAR(MAX),
@Status_924e7d98 NVARCHAR(10),
@Sequence_924e7d98 INT
SET
  @ID_924e7d98 = '89ed2a63-17ec-4418-8bae-40a4ce786248'
SET
  @Name_924e7d98 = N'Sales Discounts'
SET
  @Description_924e7d98 = N'Contra-revenue account for discounts granted on sales.'
SET
  @Status_924e7d98 = N'Active'
SET
  @Sequence_924e7d98 = 60
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_924e7d98,
  @Name = @Name_924e7d98,
  @Description = @Description_924e7d98,
  @Status = @Status_924e7d98,
  @Sequence = @Sequence_924e7d98;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_503eebc6 UNIQUEIDENTIFIER,
@Name_503eebc6 NVARCHAR(100),
@Description_503eebc6 NVARCHAR(MAX),
@Status_503eebc6 NVARCHAR(10),
@Sequence_503eebc6 INT
SET
  @ID_503eebc6 = 'a8d9e4ea-3f98-4227-9f9f-337b53ed24d3'
SET
  @Name_503eebc6 = N'Sales Returns and Allowances'
SET
  @Description_503eebc6 = N'Contra-revenue account for returned goods / allowances.'
SET
  @Status_503eebc6 = N'Active'
SET
  @Sequence_503eebc6 = 70
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_503eebc6,
  @Name = @Name_503eebc6,
  @Description = @Description_503eebc6,
  @Status = @Status_503eebc6,
  @Sequence = @Sequence_503eebc6;

GO

-- Save MJ_BizApps_Accounting: GL Account Roles (core SP call only)
DECLARE @ID_1f15eebb UNIQUEIDENTIFIER,
@Name_1f15eebb NVARCHAR(100),
@Description_1f15eebb NVARCHAR(MAX),
@Status_1f15eebb NVARCHAR(10),
@Sequence_1f15eebb INT
SET
  @ID_1f15eebb = '6d2eb237-f568-4372-8aa4-924995cd6834'
SET
  @Name_1f15eebb = N'Deferred Revenue'
SET
  @Description_1f15eebb = N'Liability account credited for revenue not yet earned (subscriptions). ASSUMED addition (OQ-H): absent from the 07-03 seed list but required by the meeting''s own subscription example - confirm with Amith.'
SET
  @Status_1f15eebb = N'Active'
SET
  @Sequence_1f15eebb = 80
EXEC [__mj_BizAppsAccounting].spCreateGLAccountRole @ID = @ID_1f15eebb,
  @Name = @Name_1f15eebb,
  @Description = @Description_1f15eebb,
  @Status = @Status_1f15eebb,
  @Sequence = @Sequence_1f15eebb;

GO

-- Save MJ: Applications (core SP call only)
DECLARE @ID_5c9f2898 UNIQUEIDENTIFIER,
@Name_5c9f2898 NVARCHAR(100),
@Description_5c9f2898 NVARCHAR(MAX),
@Icon_5c9f2898 NVARCHAR(500),
@DefaultForNewUser_5c9f2898 BIT,
@SchemaAutoAddNewEntities_5c9f2898 NVARCHAR(MAX),
@Color_5c9f2898 NVARCHAR(20),
@DefaultNavItems_5c9f2898 NVARCHAR(MAX),
@ClassName_5c9f2898 NVARCHAR(255),
@DefaultSequence_5c9f2898 INT,
@Status_5c9f2898 NVARCHAR(20),
@NavigationStyle_5c9f2898 NVARCHAR(20),
@TopNavLocation_5c9f2898 NVARCHAR(30),
@HideNavBarIconWhenActive_5c9f2898 BIT,
@Path_5c9f2898 NVARCHAR(100),
@AutoUpdatePath_5c9f2898 BIT,
@AgentSettings_5c9f2898 NVARCHAR(MAX)
SET
  @ID_5c9f2898 = '08B5D905-6FB3-438B-94E5-2C5FF021B794'
SET
  @Name_5c9f2898 = N'Accounting'
SET
  @Description_5c9f2898 = N'AR subledger, journal entries, and JE batch dispatch to the ERP'
SET
  @Icon_5c9f2898 = N'fa-solid fa-book'
SET
  @DefaultForNewUser_5c9f2898 = 0
SET
  @Color_5c9f2898 = N'#0076b6'
SET
  @DefaultNavItems_5c9f2898 = N'[
  {
    "Label": "Batches",
    "Icon": "fa-solid fa-paper-plane",
    "ResourceType": "Custom",
    "DriverClass": "BatchDispatchResource",
    "isDefault": true
  },
  {
    "Label": "Trial Balance & AR",
    "Icon": "fa-solid fa-scale-balanced",
    "ResourceType": "Custom",
    "DriverClass": "TrialBalanceARResource",
    "isDefault": false
  },
  {
    "Label": "Revenue & Tax",
    "Icon": "fa-solid fa-receipt",
    "ResourceType": "Custom",
    "DriverClass": "RevenueTaxResource",
    "isDefault": false
  },
  {
    "Label": "Batch Status",
    "Icon": "fa-solid fa-list-check",
    "ResourceType": "Custom",
    "DriverClass": "BatchStatusResource",
    "isDefault": false
  },
  {
    "Label": "Intercompany Flow",
    "Icon": "fa-solid fa-arrows-turn-to-dots",
    "ResourceType": "Custom",
    "DriverClass": "IntercompanyFlowResource",
    "isDefault": false
  },
  {
    "Label": "GL Accounts",
    "Icon": "fa-solid fa-list-tree",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: GL Accounts"
    },
    "isDefault": false
  },
  {
    "Label": "Journal Entries",
    "Icon": "fa-solid fa-book-open",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Journal Entries"
    },
    "isDefault": false
  },
  {
    "Label": "Periods",
    "Icon": "fa-solid fa-calendar-days",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Accounting Periods"
    },
    "isDefault": false
  },
  {
    "Label": "Dimensions",
    "Icon": "fa-solid fa-tags",
    "ResourceType": "User Views",
    "Configuration": {
      "Entity": "MJ_BizApps_Accounting: Dimensions"
    },
    "isDefault": false
  }
]'
SET
  @DefaultSequence_5c9f2898 = 2010
SET
  @Status_5c9f2898 = N'Active'
SET
  @NavigationStyle_5c9f2898 = N'App Switcher'
SET
  @HideNavBarIconWhenActive_5c9f2898 = 0
SET
  @Path_5c9f2898 = N'accounting'
SET
  @AutoUpdatePath_5c9f2898 = 1
EXEC [__mj].spCreateApplication @ID = @ID_5c9f2898,
  @Name = @Name_5c9f2898,
  @Description = @Description_5c9f2898,
  @Icon = @Icon_5c9f2898,
  @DefaultForNewUser = @DefaultForNewUser_5c9f2898,
  @SchemaAutoAddNewEntities = @SchemaAutoAddNewEntities_5c9f2898,
  @SchemaAutoAddNewEntities_Clear = 1,
  @Color = @Color_5c9f2898,
  @DefaultNavItems = @DefaultNavItems_5c9f2898,
  @ClassName = @ClassName_5c9f2898,
  @ClassName_Clear = 1,
  @DefaultSequence = @DefaultSequence_5c9f2898,
  @Status = @Status_5c9f2898,
  @NavigationStyle = @NavigationStyle_5c9f2898,
  @TopNavLocation = @TopNavLocation_5c9f2898,
  @TopNavLocation_Clear = 1,
  @HideNavBarIconWhenActive = @HideNavBarIconWhenActive_5c9f2898,
  @Path = @Path_5c9f2898,
  @AutoUpdatePath = @AutoUpdatePath_5c9f2898,
  @AgentSettings = @AgentSettings_5c9f2898,
  @AgentSettings_Clear = 1;

GO


-- End of SQL Logging Session
-- Session ID: 657474ba-83a8-4aeb-8e38-2614acc5b7a5
-- Completed: 2026-07-06T08:27:58.279Z
-- Duration: 913ms
-- Total Statements: 30
